devopness/devopness

- src/services/ApiBaseService.ts
* `baseUrl` field in `ConfigurationOptions` is optional.
* `baseUrl` field in `Configuration` defaults to `"https://api.devopness.com"`
> API base URL defaults to production

- src/DevopnessApiClient.ts
- src/common/Exceptions.ts
- src/index.ts
- src/services/ApiBaseService.ts
- src/services/UserService.ts
This PR attempts to make it easier for consumers to import SDK export classes.
**Main changes:**
1. Define a base `DevopnessSdkError` class and ensure all custom SDK errors extend this base type
2. Export all SDK error classes so consumers can handle them gracefully by checking the specific error types:
```javascript
if (error instanceof DevopnessSdkExceptions.NetworkError) {
// handle network error
}
if (error instanceof DevopnessSdkExceptions.ApiError) {
// handle Devopness API error
}
// or generically 
if (error instanceof DevopnessSdkExceptions.DevopnessSdkError) {
// common handler for all Devopness API SDK errors
}
```
3. Use named exports for `Models`, so consumer can import `Models` or `Models.ModelName` and make their code a bit cleaner and readable
> Error common ancestor

- tsconfig.json
The Axios `0.20.0` requires the usage of `ProgressEvent` that is declared at `DOM` builtin library of TypeScript.
> Feature/DFE-628 update SDK to load DOM builtin library

- package-lock.json
- package.json
- src/common/ApiResponse.ts
- tests/ApiResponse.spec.ts
This PR add `pageCount` attribute to `ApiResponse` class. The value is retrieved from the link `last` from `Link` header.
> Feat/DFE-779 add pageCount to ApiResponse

- src/api/generated/apis/logs-api.ts
- src/api/spec.json
Update SDK adding `getServiceStartLog` and `getServiceStopLog` operations.
> feat: add get logs to service 'start' and 'stop' actions

- openapitools.json
- package.json
- Update `build-api-models` script to be compatible with new `openapi-generator-cli` version.
- Add `openapitools.json` configuration file with the options to build API models.
- Improvements on scripts that delete folders. Using `-f` option the `rm` doesn't fail if the folder/file doesn't exist ([ref]).
[ref]: https://man7.org/linux/man-pages/man1/rm.1.html
> feat: update configurations

- README.md
This PR adds instructions to build and test the Devopness SDK locally.
> docs: Add `Building and testing` section to README

- .gitignore
- typedoc.json
Output auto-generated docs to SDK specific `/docs-sdk-*` folder, leaving root `/docs` folder reserved for official documentation to be written by this repo contributors.
> refactor: Output auto-generated docs to SDK specific folder

- .github/workflows/lint-pr-title.yml
Triggers a pull request linter to validate PR title on PRs coming from forked repositories.
This way we automatically ensure all PRs follow [Conventional Commits Specification](https://www.conventionalcommits.org/en/v1.0.0/).
P.S.: leaving the PR with the `Invalid PR title` prefix just to show how validation works. PR title will be updated after PR is approved.
> ci: Add linter to validate PR attributes

- .github/workflows/sdk-javascript-ci.yml
- .github/workflows/sdk-javascript-release.yml
> ci: Set main branch and default dir in workflows

- .github/workflows/label-pr.yml
- .github/workflows/lint-pr-title.yml
Add comments to advise on security concerns when triggering actions on `pull_request_target`.
Reference: https://securitylab.github.com/research/github-actions-preventing-pwn-requests/
> chore: Add comment on safe usage of pull_request_target

- packages/sdks/javascript/package.json
Update release branch after repo main branch being switched from `master` to `main`.
> fix: Rename release branch to use `main`

- CONTRIBUTING.md
- packages/sdks/javascript/README.md
This PR fixes:
- Some spelling errors that were found in the README.md file
- The use of the term `master`. GitHub currently use `main`
> docs: some errors in docs have been fixed

- .github/labeler-pr.yml
- docs/servers/add-existing-server.md
- docs/servers/index.md
- docs/ssh-keys/add-ssh-key.md
- docs/ssh-keys/remove-ssh-key.md
> docs: Add an existing Server

- packages/sdks/javascript/src/api/spec.json
This endpoint actually returns all hooks, both incoming and outgoing.
> fix: Fix `GET /applications/{id}/hooks` summary

- docs/cloud-provider-credentials/add-cloud-provider-credential-aws.md
Update instructions on how to generate security credentials
The current AWS IAM console doesn't have the options listed in the docs, as per the image below
So the new workflow to generate access keys using the IAM console is described in the [AWS IAM docs: Managing access keys (console)](https://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_access-keys.html#Using_CreateAccessKey), in the section "To create, modify, or delete the access keys of another IAM user (console)"
> docs: update "Add AWS Credential" instructions

- packages/sdks/javascript/README.md
A simple alteration to help macOS users to install Xcode command line.
> docs: improved instructions to install xcode in macOS

- docs/README.md
> docs: add authoring guidelines emphasizing simplicity for word choice

- docs/ssh-keys/add-ssh-key.md
- docs/ssh-keys/deploy-ssh-key.md
- docs/ssh-keys/link-ssh-key.md
Creates two new articles: "Link SSH Key" and "Deploy SSH Key". Modifies "next" link of "Add an SSH Key" to point to new "Link SSH Key" article. The goal is to clarify that after the creation of an SSH Key, it has to be deployed to a server. But first, the server must be linked to the key.
> docs: create "add a linked ssh key", "deploy ssh key" articles and modify "link ssh key"

- .github/workflows/pr-stale.yml
This PR adds a new Action which will mark issues as stale after 21 days since being opened and notify the issue creator that the issue will be closed after 14 days. Initially, this Action will be tested in debug mode with the issue being marked as stale after 1 day and deleted after 1 more day (since it's in debug mode, the notification and deletion will be a dry-run).
[DVN-13029]: https://devopness.atlassian.net/browse/DVN-13029?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: add action to handle notification and closure of stale issues

- .github/ISSUE_TEMPLATE/bug_report.yml
The 'Reproduction link' field should not be required, since not all bugs will have a reproduction link.
[DVN-13018]: https://devopness.atlassian.net/browse/DVN-13018?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> refactor: 'Reproduction link' field should not be required

- .github/labeler-issue.yml
The regex used to add the generic `sdk` label currently is matching other occurences of the string `'SDK'`  in the body of the issue. This PR adds a dash to the end of it (`SDK-`) to avoid false positive matches.
Link of issue whose labels were added automatically: https://github.com/devopness/devopness/issues/815
[DVN-13024]: https://devopness.atlassian.net/browse/DVN-13024?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: adjust regex for 'sdk' label

- docs/legal/index.md
- docs/security/index.md
This PR fixes the incorrect use of "directory" to refer to what is actually a section of the documentation by changing the wording to "section".
[DVN-13246]: https://devopness.atlassian.net/browse/DVN-13246?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: change use of word 'directory' to 'section'

- .github/PULL_REQUEST_TEMPLATE.md
- Once this change is deployed, success criteria is: template for new PRs will no longer show fields related to internal issue IDs
N/A
> docs: update PR template to link GitHub issues instead of internal issue ID

- .github/workflows/sdk-javascript-release.yml
The "npx semantic-release" command used by one of the workflows is failing due to incompatibility between the version of NodeJS used and the version required by "semantic-release". This PR updates the command so that it uses a specific version that is compatible with the NodeJS version currently used.
N/A
GitHub action responsible for updating and generating a new version of the JS SDK must work using the informed version.
N/A
> fix: define version used in semantic release

- docs/networks/remove-network.md
- Once the changes in this PR are merged and deployed, success criteria is: Update the article https://www.devopness.com/docs/networks/remove-network/
> docs: fix article "Remove a Network" to guide the user to click resource name

- docs/servers/delete-cloudprovider-server.md
- Once the changes in this PR are merged and deployed, success criteria is: Update the article https://www.devopness.com/docs/servers/delete-cloudprovider-server/
> docs: fix article "Delete a Server provisioned by Devopness" to guide the user to click resource name

- packages/ui/react/src/components/Buttons/Button/Button.stories.ts
- packages/ui/react/src/components/Buttons/Button/Button.tsx
- packages/ui/react/src/icons/iconLoader.test.ts
- packages/ui/react/src/icons/iconLoader.test.tsx
- packages/ui/react/src/icons/iconLoader.tsx
- Fix fail to render Button with the props below [1]
```tsx
<Button
buttonType="Default"
onClick={() => {}}
typeSize="default"
loading={false}
>
Add Application
</Button>
```
The button above has no icon and is explicitly not loading
N/A
- Once the changes in this PR are merged and deployed, success criteria is: A Button can be rendered without an icon and not loading with no errors
[1]
BEFORE:
No Icon
With Icon
AFTER:
No Icon
https://thlmenezes-storybook.devopness.com/?path=/story/buttons-button--primary&args=loading:!false
With Icon
https://thlmenezes-storybook.devopness.com/?path=/story/buttons-button--primary&args=icon:plus;loading:!false
Error begins here
https://github.com/devopness/devopness/blob/ca0974175098fed40ea2b8ac9b0c4b85061494b0/packages/ui/react/src/components/Buttons/Butto …
> fix(design-sytem): fail to render Button without an icon

- .github/workflows/sdk-javascript-ci.yml
- .github/workflows/sdk-javascript-release.yml
- .github/workflows/ui-react-ci.yml
- .github/workflows/ui-react-release.yml
- Fixes building packages twice per action [1]
N/A
- Once the changes in this PR are merged and deployed, success criteria is: All package related workflows should run prepare/build scripts only once
[1]
`prepare` script is called during `npm ci` unless adding `--ignore-scripts` flag
https://docs.npmjs.com/cli/v8/using-npm/scripts#npm-ci
https://docs.npmjs.com/cli/v8/commands/npm-ci#ignore-scripts
- SDK JavaScript https://github.com/devopness/devopness/actions/runs/11041350259/job/30671424291
- UI React https://github.com/devopness/devopness/actions/runs/11244451650/job/31262550259
`npm ci`
`npx semantic-release@22.0.12`
- SDK JavaScript https://github.com/devopness/devopness/actions/runs/11224903987/job/31202571452
- UI React https://github.com/devopness/devopness/actions/runs/11244458565 …
> ci: avoid building packages sdk-js and ui-react 2 times per action

- package-lock.json
- packages/ui/react/package.json
- Bump typescript-eslint from 8.18.1 to 8.19.0
- Fixes CI error during lint step "cannot find module eslint/use-at-your-own-risk"
- This error was introduced in #1091
- N/A
- Once the changes in this PR are merged and deployed, success criteria is: CI should run ESLint without errors
https://github.com/devopness/devopness/actions/runs/12540685127/job/34981818490
https://github.com/devopness/devopness/actions/runs/12547400297/job/34984803292
> fix(eslint): bump typescript-eslint from 8.18.1 to 8.19.0

- .changeset/fix-Alert-export.md
- packages/ui/react/src/components/index.ts
- Fix Alert component export in main index.ts file, allowing users to import it directly from '@devopness/ui-react' instead of requiring the full component path
N/A
- Alert component can be imported directly from '@devopness/ui-react'
- Existing Alert component functionality remains unchanged
While implementing the Alert component in a previous PR, I missed adding its export in the package's main entry point. This caused the component to be inaccessible through the standard import path from '@devopness/ui-react', despite being properly implemented in the Forms directory.
This fix ensures the component is properly exported through the main index.ts, allowing it to be imported using the standard pattern: `import { …
> fix(design-system): properly export Alert component from root path

- .changeset/replace-react-icons-all-files.md
- package-lock.json
- packages/ui/react/.storybook/preview.ts
- packages/ui/react/package.json
- packages/ui/react/src/components/Primitives/Icon/Icon.stories.tsx
- packages/ui/react/src/components/Primitives/Label/Label.styled.ts
- packages/ui/react/src/icons/iconLoader.tsx
- Replace dependency `@react-icons/all-files` with `react-icons`
- The `@react-icons/all-files` approach...
- ...is not recommend "for standard modern project", according to [docs](https://react-icons.github.io/react-icons/)
- ...is slower to install, compared to `react-icons`
- ...needs to download a big file from outside npm registry
- Due to those reasons, and aiming to reduce install times of this library, it's recommended to avoid `@react-icons/all-files`
- Fixes Icon story colors [1]
- Sort Storybook Controls by showing required props first and sorting all alphabetically
- See [Storybook Docs: Controls - Sorting Controls](https://storybook.js.org/docs/essentials/controls#sorting-controls)
- Add default 100% opacity to story
N/A
- Once the changes in this PR are merged and deployed, …
> feat(design-system): update icons source from @react-icons/all-files to react-icons

- .changeset/shaggy-plums-smash.md
- packages/ui/react/src/components/Buttons/Button/Button.styled.ts
- packages/ui/react/src/components/Buttons/Button/Button.tsx
- packages/ui/react/src/components/Forms/Alert/Alert.tsx
- packages/ui/react/src/components/Primitives/Dropdown/Dropdown.tsx
- packages/ui/react/src/components/Primitives/Pagination/Pagination.tsx
Fixes bug described in issue #1004, where unwanted props used only in internal styling logic are currently being propagated by Styled Components to the DOM.
- Updated prop name in typing for BaseButton styled component, prefixing "$" to old prop name.
- looking at the resulting `<button />` DOM element from a `Button` component and noting that there are no props there that are invalid attributes.
-  looking at the dev console and noting that there are no related warnings from react or styled-components regarding the button props.
This was solved as suggested in the issue description, by using the prop name to signal to Styled Components that the prop in question is a [transient …
> fix: stop unwanted props from propagating to DOM Element in Button

- .changeset/fix-button-props.md
- packages/ui/react/src/components/Buttons/Button/Button.styled.ts
- packages/ui/react/src/components/Buttons/Button/Button.test.tsx
- packages/ui/react/src/components/Buttons/Button/Button.tsx
- packages/ui/react/src/components/Forms/Alert/Alert.tsx
- packages/ui/react/src/components/Primitives/Dropdown/Dropdown.tsx
- packages/ui/react/src/components/Primitives/Pagination/Pagination.tsx
- Fix breaking changes in Button [1]
- Reverted changes made directly to ButtonProps in #1179 [1]
- Update Button test suite
- The updated test suite has a higher code coverage [2]
- This change aims to help detect future breaking changes in props
- Removed unused styles declared in Button.styled.ts
- Sorted and commented style code, to improve legibility
N/A
- Once the changes in this PR are merged and deployed, success criteria is: The updated Button should be compatible with v2.153.0 version, enabling users to update the dependency without needing to update props
[1]
Revert the changes below to ButtonProps, that added the prefix "$", from styled component transient props
```
$noMargin?: boolean
/**
* The button component has a 10px margin on its sides, to remove activate the …
```
> fix(design-system): revert #1179 breaking changes and refactor implementation to improve legibility

- .github/workflows/pr-lint.yml
- N/A  
- Once the changes in this PR are merged and deployed, the success criteria is: the CI job 'Validate PR Title' runs correctly on PRs.
> fix: validate pr-title job name

- .github/workflows/pr-lint.yml
- N/A  
- Once the changes in this PR are merged and deployed, the success criteria is: PRs from the user [github-actions](https://github.com/apps/github-actions) will no longer be checked by the `PR Lint` CI.  
- PR from [github-actions](https://github.com/apps/github-actions) blocked by the `PR Lint` CI - [#1257](https://github.com/devopness/devopness/actions/runs/13040682748/job/36381621847?pr=1257)
> fix: update PR validation to exclude 'github-actions' user from checks

- .github/workflows/pr-lint.yml
- N/A  
- Once the changes in this PR are merged and deployed, the success criteria is: PRs from the user [github-actions](https://github.com/apps/github-actions) will no longer be checked by the `PR Title` CI.  
- PR from [github-actions](https://github.com/apps/github-actions) blocked by the `PR Title` CI - [#1257](https://github.com/devopness/devopness/actions/runs/13040682748/job/36381621847?pr=1257)
> fix: update PR title to exclude 'github-actions' user from checks

- docs/servers/add-gcp-server.md
This PR fixes a minor typo in the documentation for improved clarity and professionalism.  
- Updated wording from **“On GCP console”** to **“On the GCP console”** to reflect proper grammar and enhance readability.
- Once the changes in this PR are merged and deployed, success criteria is:  
The typo is corrected, and the documentation displays the improved sentence: **“On the GCP console…”**
Minor documentation fix, no functional changes. No additional dependencies or steps required.
> docs: Fix typos in cloud provider instructions

- .changeset/add-card-header-prop.md
- packages/ui/react/src/components/Templates/Card/Card.styled.ts
- packages/ui/react/src/components/Templates/Card/Card.test.tsx
- packages/ui/react/src/components/Templates/Card/Card.tsx
- Introduced a new `borderBottomColor` prop in the Card component's `headerProps` for enhanced styling flexibility.
- Updated the styled component to apply the new border color while maintaining existing functionality.
- Added tests to verify the correct application of the new border color in various scenarios.
This change allows users to independently control the header's border color, improving the customization options for the Card component.
- N/A
- Once the changes in this PR are merged and deployed, success criteria is: Card header border bottom color will be customizable
> feat(design-system): add `borderBottomColor` prop to customize Card header

- .changeset/fix-shield-lock-icon-runtime-error.md
- packages/ui/react/src/icons/iconLoader.tsx
- Fixes error when attempting to use `shieldLock` icon
- Read more @ changeset file
- N/A
- Once the changes in this PR are merged and deployed, success criteria is: Users will now be able to use `shieldLock` icon without errors
https://thlmenezes-storybook.devopness.com/?path=/story/primitives-icon--primary&args=name:shieldLock
> fix(design-system): runtime error rendering `shieldLock` icon

- .github/workflows/pr-auto-merge-dependabot.yml
- N/A
- Once the changes in this PR are merged and deployed, success criteria is: Dependabot PR's for patch updates are automatically merged without manual intervention.
> feat: add workflow to auto-merge Dependabot PRs for Patch Updates

- .github/workflows/pr-auto-merge-dependabot.yml
- N/A
- Once the changes in this PR are merged and deployed, success criteria is: Dependabot PRs will successfully auto-merge using squash strategy.
This change was necessary because GitHub threw the following error when attempting to merge using --merge:
```ruby
GraphQL: Merge method merge commits are not allowed on this repository
and Pull request User is not authorized for this protected branch (enablePullRequestAutoMerge)
```
Now, with --squash, merges comply with repository policy and unblock automation workflows.
> fix(ci): change Dependabot auto-merge strategy to use squash

- packages/sdks/python/.version
- packages/sdks/python/README.md
- packages/sdks/python/devopness/common/__init__.py
- packages/sdks/python/devopness/models/__init__.py
- packages/sdks/python/devopness/services/__init__.py
- packages/sdks/python/pyproject.toml
- packages/sdks/python/scripts/post-build.sh
- packages/sdks/python/scripts/publish-dev.sh
- N/A
- Consumers can now import SDK modules using simplified import paths (e.g., **from devopness.models import ApiResponse**) without **PrivateImport** Warning.
- The SDK can be published to TestPyPI using **./scripts/publish-dev.sh** without updating **pyproject.toml**
- TestPyPI Package: https://test.pypi.org/project/devopness/
> fix(sdk-python): module exports and add version control for dev-package

- docs/team-memberships/add-team-membership.md
- docs/team-memberships/list-team-memberships.md
This PR fixes the new documentation topics added on #1624 that were breaking the build for not including the docs folder in `previous` links.
- [z] closes #1217
- Once the changes in this PR are merged and deployed, success criteria is: no more errors related to "pagination_prev front matter points to a non-existent ID" during the build of documentation website
> fix: `TEAM MEMBERSHIP` docs paths in `previous` links

- packages/sdks/python/.version
- packages/sdks/python/poetry.lock
- packages/sdks/python/pyproject.toml
Although httpcore was previously an indirect dependency (through httpx), this change makes it a direct dependency to guarantee the patched version is installed by any downstream project using this SDK.
- **httpx** accepts any **httpcore** version in the **1.*** range
- **httpcore>=1.0.9** depends on **h11>=0.16**, which includes the security fix
By making httpcore a direct dependency, we ensure users of this SDK receive the secure h11 version, even if their own dependency resolver would have otherwise allowed an older httpcore.
- The h11 dependency of the Devopness SDK - Python is updated to the version with the security fix
> fix: update h11 to fix security/dependabot #63

- package-lock.json
- packages/sdks/python/package.json
This PR ensures the lock file is aligned with package.json, preventing errors such as:
```ruby
npm ci can only install packages when your package.json
and package-lock.json or npm-shrinkwrap.json are in sync.
Missing: @devopness/sdk-python@0.0.0 from lock file  
```
- N/A
- Once the changes in this PR are merged and deployed, success criteria is: publish pipeline work normally.
CI failure details can be found in the workflow run logs: https://github.com/devopness/devopness/actions/runs/15077237309/job/42387322168
> fix(package-lock): rename sdk-python-dev to sdk-python

- .github/workflows/issue-stale.yml
- Pull requests with 7 days of inactivity will be automatically labeled as stale
- Stale pull requests will receive a clear notification message
- If a stale PR remains inactive for 14 more days, it will be automatically closed
- If a stale PR receives any updates, the stale label will be automatically removed
This PR configures the workflow with a 7-day threshold for marking PRs as stale and a 14-day period before closing. This helps keep the repository clean by automatically handling abandoned pull requests while giving authors sufficient time to respond.
> ci: Enable stale workflow for PRs to close abandoned pull requests

- .github/workflows/pr-auto-merge-dependabot.yml
- This PR aims to add one more action to  `PR - Auto Merge Dependabot` action, this change is necessary to integrate to others github-actions as mentioned [here](https://github.com/devopness/devopness-web-app/pull/1181#discussion_r2097163802)
- N/A
- Once the changes in this PR are merged and deployed, success criteria is: after the merge the action will have another trigger to run, this will allow to run this action manually.
> feat(ci): add workflow_dispatch trigger to PR - Auto Merge Dependabot action

- .changeset/soft-insects-return.md
- packages/sdks/python/src/devopness/client_config.py
- packages/sdks/python/tests/unit/test_client_config.py
When instantiating the **DevopnessClientConfig**, if an invalid **base_url** is provided (i.e., it doesn't start with **http://** or **https://**), a clear validation error is now raised.
This prevents runtime misconfigurations and helps users catch mistakes earlier when configuring the SDK.
- N/A
- Once the changes in this PR are merged and deployed, success criteria is: Users providing an invalid **base_url** receive an informative error early during SDK initialization.
> feat(sdk-python): validate base_url format in DevopnessClientConfig

- packages/ai/mcp-server/Dockerfile
- packages/ai/mcp-server/Makefile
- packages/ai/mcp-server/devopness_api.py
- packages/ai/mcp-server/main.py
- packages/ai/mcp-server/pyproject.toml
- packages/ai/mcp-server/server.py
- packages/ai/mcp-server/uv.lock
This PR introduces foundational tooling improvements for the devopness-mcp-server project:
These changes make it easier for contributors to get started quickly, ensure consistent code quality, and reduce setup friction across developer environments.
- N/A
-  Developers can run make shell, make lint, and make format in any environment consistently
> chore: add Dockerfile, Makefile, and linting/formatting tools

- .github/workflows/sync-package-versions.yml
- package-lock.json
- packages/ai/mcp-server/package.json
- packages/ai/mcp-server/pyproject.toml
- packages/ai/mcp-server/uv.lock
Example of a failed `Release - Packages` run caused by a missing version sync:
* ❌ [Failed `Release - Packages` run](https://github.com/devopness/devopness/actions/runs/15611356857/job/43972799463)
* ⚠️ [Auto-merged PR that caused the failure](https://github.com/devopness/devopness/pull/1848)
* N/A
* Once the changes in this PR are merged and deployed, success criteria is:
* The `verify-sync` job blocks merges if the sync step fails, preventing unsynced version issues in the release pipeline
> fix: make 'sync - package versions' a required workflow for pr targeting main

- .changeset/lovely-carrots-look.md
- packages/ai/mcp-server/src/devopness_mcp_server/lib/tools.py
- N/A
- A server can be provisioned with the updated `devopness_create_cloud_server` flow
- LLM/User can list regions and instance types and select using natural language queries (e.g., "cheapest Azure instance type with at least 4GB RAM in eastus2")
> feat(mcp-server): enhance cloud server provisioning with region/instance discovery

- .changeset/good-sheep-itch.md
- packages/ai/mcp-server/src/devopness_mcp_server/lib/services/application_service.py
- N/A
- Users will be able to create application environment variables and configuration files via the new tools added to the MCP Server
> feat(mcp-server): add tools to create application variables and config files

- .changeset/healthy-horses-whisper.md
- packages/ai/mcp-server/src/devopness_mcp_server/lib/models.py
- packages/ai/mcp-server/src/devopness_mcp_server/lib/services/environment_service.py
- packages/ai/mcp-server/src/devopness_mcp_server/lib/services/project_service.py
Project and environment listings were returning too much data, causing the LLM to skip or hallucinate items.
We now return only summary fields (`id`, `name`, `description`) and added a `page` argument to support pagination.
- N/A
- Once the changes in this PR are merged and deployed, success criteria is: LLM should now list all projects/environments correctly, with no omissions or hallucinations.
> refactor(mcp-server): use summaries and add pagination to list projects and environments

- .changeset/eighty-trainers-hang.md
- packages/ai/mcp-server/src/devopness_mcp_server/lib/services/application_service.py
- packages/ai/mcp-server/src/devopness_mcp_server/lib/services/server_service.py
- N/A
- LLMs receive precise validation feedback when creating an application, know what to do next through suggested actions, and can retrieve valid runtime options via the new tool
> refactor(mcp-server): improve 'create application' tool with validation and runtime suggestions

- .changeset/rich-ways-love.md
- packages/ai/mcp-server/pyproject.toml
- packages/ai/mcp-server/uv.lock
- N/A
- MCP Server will rely on `devopness@1.2.1`, reflecting the latest available changes.
> chore(mcp-server): bump devopness dependency version to 1.2.1

- .changeset/heavy-experts-attack.md
- packages/ai/mcp-server/src/devopness_mcp_server/lib/models.py
- packages/ai/mcp-server/src/devopness_mcp_server/lib/services/application_service.py
- packages/ai/mcp-server/src/devopness_mcp_server/lib/services/credential_service.py
- packages/ai/mcp-server/src/devopness_mcp_server/lib/services/daemon_service.py
- packages/ai/mcp-server/src/devopness_mcp_server/lib/services/environment_service.py
- packages/ai/mcp-server/src/devopness_mcp_server/lib/services/pipeline_service.py
- packages/ai/mcp-server/src/devopness_mcp_server/lib/services/project_service.py
- packages/ai/mcp-server/src/devopness_mcp_server/lib/services/server_service.py
- packages/ai/mcp-server/src/devopness_mcp_server/lib/services/service_service.py
- packages/ai/mcp-server/src/devopness_mcp_server/lib/services/virtual_host_service.py
- packages/ai/mcp-server/src/devopness_mcp_server/lib/tools.py
- packages/ai/mcp-server/src/devopness_mcp_server/lib/types.py
- packages/ai/mcp-server/src/devopness_mcp_server/lib/utils.py
- N/A
- The LLM successfully guides users to list, create, and deploy daemon and virtual-host resources
- The LLM never assumes project/environment IDs without user confirmation
**Before**
**After**
> feat(mcp-server): add support for daemon and virtual host and improve 'resource list ux'

- .github/workflows/ci-cla-assistant.yml
- N/A
- Once the changes in this PR are merged and deployed, success criteria is: CLA action is triggered using version 2.6.1
> ci: bump `contributor-assistant` action to 2.6.1

- docs/docs/ssh-keys/list-ssh-keys.md
- docs/docs/ssh-keys/view-ssh-key.md
- Added two new documentation pages for the SSH Keys section:
- Listing SSH Keys
- Viewing SSH Key details
- These additions help fill existing gaps in the SSH Keys documentation.
- The new documentation pages appear correctly in the SSH Keys section on the Devopness Docs site.
- Content is properly formatted and renders as expected in Docusaurus.
- Links between related SSH Keys pages work correctly.
N/A
> docs(ssh-keys): add pages for listing and viewing SSH keys

- .github/workflows/sync-package-versions.yml
This updates the trigger for the `Sync - Package Versions` workflow from ['pull_request' to 'pull_request_target'](https://runs-on.com/github-actions/pull-request-vs-pull-request-target/).
The reason for this change is that when using `pull_request`, GitHub does **not expose repository secrets** (like `DEVOPNESS_PYPI_PACKAGES`) to workflows triggered by forks — causing the workflow to fail.
- N/A
- The `Sync - Package Versions` workflow completes successfully for PRs opened from forks and has access to the `DEVOPNESS_PYPI_PACKAGES` secret.
> fix: 'Sync - Package Versions' to work with PRs from forks

- .changeset/add-hetzner-and-fastmcp-icons.md
- packages/ui/react/src/icons/iconLoader.tsx
This PR updates the icon set in @devopness/ui-react by adding two new icons:
- hetzner
- fastmcp
- Once the changes in this PR are merged and deployed, success criteria is: The hetzner and fastmcp icons should render correctly when used with the Icon component.
These additions expand the available icon library for use across the application, ensuring consistent branding and visual representation for services and integrations.
> feat: add hetzner and fastmcp icons

- docs/docs/credentials/add-hetzner-credential.md
This PR adds a new documentation page explaining how to generate a Hetzner API token and add it as a credential in Devopness.
- The page guides users step by step through logging into Hetzner Cloud, generating a new API token with the appropriate permissions (Read & Write), and copying the token.
- It also explains how to add the token to Devopness and includes links to official Hetzner documentation.
- Best practices for naming and managing the token are also included to improve clarity for users.
- N/A
- Once the changes in this PR are merged and deployed, success criteria is: The new Add Hetzner Credential documentation page is accessible from the Docs section and users can follow the instructions to generate a Hetzner API token and successfully add it to Devopness.
> docs(heztner-credential): add heztner credential page

- docs/docs/credentials/add-hetzner-credential.md
- This PR updates the documentation to clarify the `API Token` setup process by adding an explicit step instructing users to **access or create a project** before navigating to the **Security** section.  
- N/A
- Once the changes in this PR are merged and deployed, success criteria is: Documentation clearly instructs users to **create or select a project** before accessing the `Security` panel.
> refactor(docs): add access/create project step

- README.md
- Once the changes in this PR are merged and deployed, success criteria is: when the user clicks on **Add to Cursor**, they are correctly redirected to the installation page of the Devopness MCP Server in Cursor.
https://github.com/user-attachments/assets/03af1e48-8ed0-485a-b1a1-71dab684f37e
https://github.com/user-attachments/assets/96b1a8b3-7bfd-47d4-bd03-92fb670fc0e3
> fix: 'add to cursor' button link

- .changeset/add-form-text-component.md
- packages/ui/react/src/components/Forms/FormText/FormText.stories.tsx
- packages/ui/react/src/components/Forms/FormText/FormText.styled.ts
- packages/ui/react/src/components/Forms/FormText/FormText.test.tsx
- packages/ui/react/src/components/Forms/FormText/FormText.tsx
- packages/ui/react/src/components/Forms/FormText/index.ts
- packages/ui/react/src/components/Forms/index.ts
* Adds a new `FormText` component to the application that provides:
* A section title with optional subtitle.
* Support for custom subtitle color.
* An optional divider line for improved visual separation in forms.
- Once the changes in this PR are merged and deployed, success criteria is: The `FormText` component correctly renders titles, subtitles (with and without custom colors), and divider line across all use cases without breaking existing form layouts.
> feat(design-system): add FormText component

- .changeset/add-illustration-component.md
- packages/ui/react/src/components/Forms/Illustration/Illustration.stories.tsx
- packages/ui/react/src/components/Forms/Illustration/Illustration.styled.ts
- packages/ui/react/src/components/Forms/Illustration/Illustration.test.tsx
- packages/ui/react/src/components/Forms/Illustration/Illustration.tsx
- packages/ui/react/src/components/Forms/Illustration/__snapshots__/Illustration.test.tsx.snap
- packages/ui/react/src/components/Forms/Illustration/index.ts
- packages/ui/react/src/components/Forms/index.ts
* Adds a new `Illustration` component to the application that provides:
* A centered layout for its children, both horizontally and vertically.
* A fixed height of `126px` and full width.
* A bottom border styled with the theme color `slate.300`.
- Once the changes in this PR are merged and deployed, success criteria is: The `Illustration` component correctly centers its children, applies the fixed height and full width, and renders the bottom border consistently across the application.
> feat(design-system): add Illustration component
