- package-lock.json
- package.json
- src/common/Exceptions.ts
- src/services/ApiBaseService.ts
- tests/Exceptions.spec.ts
* Adds `NetworkError` type, raised when a network error or timeout happens.
* Unit tests using `axios-mock-adapter`.
> NetworkError type

- src/DevopnessApiClient.ts
* also sort alphabetically lines referring to services
> Expose ApplicationService in DevopnessApiClient

- src/services/ProjectService.ts
`projects.applications` is a `ProjectsApplicationsApiService`
> Exposes applications in ProjectService

- package-lock.json
- package.json
* adds [husky](https://github.com/typicode/husky) as dev dependency
* runs `npm run build` as a git pre-push hook.
> git pre-push hook with husky

- src/api/generated/models/application.ts
- src/api/generated/models/environment.ts
- src/api/generated/models/server.ts
- src/api/spec.json
Update `Application`, `Environment` and `Server` models to expose `created_by_user` field.
> feat: update models

- src/api/generated/models/application.ts
- src/api/generated/models/cron-job.ts
- src/api/generated/models/daemon.ts
- src/api/generated/models/deployment.ts
- src/api/generated/models/network-rule.ts
- src/api/generated/models/server.ts
- src/api/generated/models/service.ts
- src/api/generated/models/ssh-key.ts
- src/api/generated/models/ssl-certificate.ts
- src/api/spec.json
Update models adding `last_action` attribute and removing `actions`.
> Feat/DGF-370 update models adding last_action attribute

- src/api/generated/models/action-step.ts
- src/api/generated/models/server-action.ts
- src/api/spec.json
- Update `ActionStep` model
- Update `ServerAction` model
> Feat/DGF-900 update ActionStep and ServerAction models

- src/api/generated/models/cloud-service.ts
- src/api/generated/models/server-options.ts
- src/api/spec.json
- Remove `os` from `ServerOptions` model
- Add `os` to `CloudService` model
> feat: update ServerOptions and CloudService models

- src/api/generated/models/application.ts
- src/api/generated/models/cron-job.ts
- src/api/generated/models/daemon.ts
- src/api/generated/models/deployment.ts
- src/api/generated/models/hook.ts
- src/api/generated/models/invitation.ts
- src/api/generated/models/network-rule-create.ts
- src/api/generated/models/network-rule-relation.ts
- src/api/generated/models/network-rule.ts
- src/api/generated/models/project.ts
- src/api/generated/models/server.ts
- src/api/generated/models/service.ts
- src/api/generated/models/ssh-key.ts
- src/api/generated/models/ssl-certificate.ts
- src/api/spec.json
* Make model's relations required.
* Update `ip_address_from` and `ip_address_to` of `NetworkRule` model to make it nullable.
> feat: update model's relations

- CONTRIBUTING.md
This adds small changes to the text in the CONTRIBUTING.md file in order to make it clearer, without changing the meaning of any sentence.
> docs: add text change suggestions for contributing.md

- docs/environments/add-environment.md
- docs/environments/index.md
- docs/projects/add-project.md
- docs/projects/index.md
> docs: Instructions for adding project and environments

- docs/cloud-provider-credentials/add-cloud-providers-credentials.md
- docs/servers/add-gcp-server.md
⚡ This PR fixes a line break in 2 yaml files that caused the devopness-site doc to not run correctly
> fix: fixing yaml line break in docs

- packages/sdks/javascript/package-lock.json
- packages/sdks/javascript/package.json
Remove `eslint-plugin-standard`
> feat: Upgrade ts eslint

- packages/sdks/javascript/package-lock.json
- packages/sdks/javascript/package.json
> feat: Upgrade Jest and related packages

- docs/cloud-provider-credentials/add-cloud-provider-credential.md
- docs/cloud-provider-credentials/get-gcp-service-account-credential.md
- docs/cloud-provider-credentials/index.md
- docs/cloud-provider-credentials/remove-cloud-provider-credential.md
- docs/servers/add-aws-server.md
- docs/servers/add-gcp-server.md
Add instructions on how to Add Server to AWS
> docs: Add AWS server

- docs/applications/add-application.md
- docs/applications/index.md
Add instructions on how to Add Applications
> docs: Add application

- docs/cloud-provider-credentials/add-cloud-provider-credential-aws.md
- docs/cloud-provider-credentials/add-cloud-provider-credential-gcp.md
- docs/cloud-provider-credentials/add-cloud-provider-credential.md
- docs/cloud-provider-credentials/index.md
> docs: Add AWS credentials guide

- .editorconfig
- .github/workflows/sdk-javascript-ci.yml
Also add `.editorconfig` to ensure YAML files use single quotes.
> ci: Trigger CI for SDK-JS on PRs only

- packages/sdks/javascript/src/api/generated/apis/environments-servers-api.ts
- packages/sdks/javascript/src/api/generated/apis/sshkeys-api.ts
- packages/sdks/javascript/src/api/generated/models/ssh-key-update.ts
- packages/sdks/javascript/src/api/spec.json
> feat: 2022-10-26 20:38 - Update API specification

- docs/applications/add-ssl-certificate.md
Instructions to add and SSL certificate to a Devopness application.
> docs: Add an SSL certificate to an application

- .github/workflows/sdk-javascript-ci.yml
- packages/sdks/javascript/src/api/generated/apis/pipelines-steps-api.ts
- packages/sdks/javascript/src/api/generated/models/daemon-update.ts
- packages/sdks/javascript/src/api/generated/models/variable-update.ts
- packages/sdks/javascript/src/api/spec.json
> feat: 2022-11-11 08:04 - Update API specification

- packages/sdks/javascript/src/api/generated/apis/pipelines-steps-api.ts
- packages/sdks/javascript/src/api/spec.json
> feat: 2022-11-11 10:44 - Update API specification

- packages/sdks/javascript/src/api/generated/models/variable-target.ts
- packages/sdks/javascript/src/api/spec.json
> feat: 2022-12-07 01:23 - Update API specification

- packages/sdks/javascript/src/api/generated/apis/environments-servers-api.ts
- packages/sdks/javascript/src/api/generated/models/application-environment-create.ts
- packages/sdks/javascript/src/api/generated/models/application.ts
- packages/sdks/javascript/src/api/generated/models/cron-job-environment-create.ts
- packages/sdks/javascript/src/api/generated/models/cron-job-update.ts
- packages/sdks/javascript/src/api/generated/models/cron-job.ts
- packages/sdks/javascript/src/api/generated/models/daemon-environment-create.ts
- packages/sdks/javascript/src/api/generated/models/daemon-update.ts
- packages/sdks/javascript/src/api/generated/models/daemon.ts
- packages/sdks/javascript/src/api/generated/models/network-rule-environment-create.ts
- packages/sdks/javascript/src/api/generated/models/network-rule-update.ts
- packages/sdks/javascript/src/api/generated/models/network-rule.ts
- packages/sdks/javascript/src/api/generated/models/server.ts
- packages/sdks/javascript/src/api/generated/models/service-environment-create.ts
- packages/sdks/javascript/src/api/generated/models/service-update.ts
- packages/sdks/javascript/src/api/generated/models/service.ts
- packages/sdks/javascript/src/api/generated/models/ssh-key-environment-create.ts
- packages/sdks/javascript/src/api/generated/models/ssh-key-update.ts
- packages/sdks/javascript/src/api/generated/models/ssh-key.ts
- packages/sdks/javascript/src/api/generated/models/variable-relation.ts
- packages/sdks/javascript/src/api/generated/models/variable.ts
- packages/sdks/javascript/src/api/spec.json
> feat: 2022-12-16 19:58 - Update API specification

- README.md
- packages/sdks/javascript/Dockerfile-dev
- packages/sdks/javascript/Makefile
- packages/sdks/javascript/README.md
- packages/sdks/javascript/package.json
To improve the read experience i highlighted some sentences.
The phrase "Java Runtime Environment" was half erased among several others. One sentence very important to build the SDK correctly
The TypeScript Support has some very important conditions and i highlighted.
These are just a few examples I made to improve the reading experience, there are others, but it's not productive to list them all here.
I added Docker Support with Makefile and update README to explain how execute the commands
> feat: change some styles of the readme to improve the read experience and Docker support

- packages/sdks/javascript/src/api/generated/apis/users-api.ts
- packages/sdks/javascript/src/api/spec.json
> feat: 2023-01-11 10:48 - Update API specification

- packages/sdks/javascript/src/services/StaticService.ts
fix: export new endpoint `GET static/user-profile-options`
> fix: export new endpoint user-profile-options

- docs/environments/add-environment.md
- docs/environments/add-teams-to-environment.md
- docs/roles/add-role.md
- docs/roles/index.md
- docs/teams/add-member-to-team.md
- docs/teams/add-team.md
- docs/teams/index.md
> docs: `Teams`, `Roles` and `Team Membership`

- docs/roles/add-role.md
The Roles flow in the web-app has been updated, following the same pattern as the Environments and Teams cards within a project. With this, it is necessary to correct the documentation so that the user follows the updated flow.
> fix: updated flow to find Roles in project

- packages/sdks/javascript/src/api/generated/apis/resource-links-api.ts
- packages/sdks/javascript/src/api/generated/models/resource-link-relation.ts
- packages/sdks/javascript/src/api/spec.json
> feat: 2023-03-25 01:06 - Update API specifications

- packages/sdks/javascript/src/api/generated/models/credits.ts
- packages/sdks/javascript/src/api/spec.json
> feat: 2023-04-27 14:23 -  Update API specification

- docs/cloud-provider-credentials/add-cloud-provider-credential.md
- docs/pipelines/add-pipeline-step.md
- docs/pipelines/add-pipeline.md
- docs/pipelines/edit-pipeline.md
- docs/pipelines/index.md
- docs/pipelines/remove-pipeline-step.md
- docs/pipelines/remove-pipeline.md
Add instructions on how to add, edit and remove pipeline and pipeline steps
<details>
<summary>More info to help validate your PR: links, images, videos, ...</summary>
Before
After
</details>
[DVN-10220]: https://devopness.atlassian.net/browse/DVN-10220?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DVN-10221]: https://devopness.atlassian.net/browse/DVN-10221?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DVN-10222]: https://devopness.atlassian.net/browse/DVN-10222?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> docs: add pipeline crud instructions

- docs/environments/add-teams-to-environment.md
Add previous link to last post on introduction guide
N/A
<details>
<summary>More info to help validate your PR: links, images, videos, ...</summary>
Last post is not connected to the guide
</details>
> docs: add previous link on add-teams-to-environment post

- docs/roles/add-role.md
Use quote to add more information to step, following the same pattern seen in other pages, examples in more info
N/A
<details>
<summary>More info to help validate your PR: links, images, videos, ...</summary>
Add Role
SSH into server
</details>
> docs: use quote on add-role post

- docs/applications/deploy-application.md
Add instruction on how to deploy an application via Devopness
<details>
<summary>More info to help validate your PR: links, images, videos, ...</summary>
</details>
[DVN-10372]: https://devopness.atlassian.net/browse/DVN-10372?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DVN-10373]: https://devopness.atlassian.net/browse/DVN-10373?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> docs: add deploy post

- .github/PULL_REQUEST_TEMPLATE.md
Update PR template, giving more visibility to the "More info" section
N/A
This PR uses the updated template
> feat: update PULL_REQUEST_TEMPLATE.md

- docs/pipelines/add-pipeline-step.md
Typo in docs, pipelines in plural should be used
N/A
> docs: update add-pipeline-step.md

- docs/api/index.md
Create a post to link to API docs from the main documentation website
N/A
> docs: add API docs index post

- packages/sdks/javascript/src/api/spec.json
> chore: add tag for Static Data - Resource Types

- docs/api/find-your-activity-summary.md
- docs/api/index.md
Improved wording on guiding the user to make API calls
N/A
> docs: improved wording on guiding users to make api requests

- docs/cloud-provider-credentials/add-cloud-provider-credential-gcp.md
Fixes "Add Google Cloud Platform Credential" post items numbering between steps 7 and 8
> docs: update add-cloud-provider-credential-gcp.md

- packages/sdks/javascript/src/api/generated/models/pipeline-create.ts
- packages/sdks/javascript/src/api/generated/models/pipeline-relation.ts
- packages/sdks/javascript/src/api/generated/models/pipeline.ts
- packages/sdks/javascript/src/api/spec.json
> feat: 2023-06-07 00:34 -  Update API specification 

- packages/sdks/javascript/src/api/generated/apis/servers-api.ts
- packages/sdks/javascript/src/api/spec.json
> feat: 2023-06-07 03:23 - Update API specification 

- docs/configuration-files/add-configuration-file.md
Capitalize title to match other posts in the same section
N/A
"Add a configuration file" post in production
"Edit a Configuration File" post in production, with capitalized title
> docs: capitalize "add configuration file" post title

- packages/sdks/javascript/README.md
Add a new step on Docker local setup instructions orienting the user to change to the project directory once they have Dockerfiles and Makefiles.
Eliminate possibility of misunderstanding arising from the fact only  "without docker" instructions oriented to cd into packages/sdks/javascript.
Post preview
> docs: Improve docker setup instructions

- docs/configuration-files/add-configuration-file.md
- docs/configuration-files/edit-configuration-file.md
- docs/configuration-files/remove-configuration-file.md
- docs/pipelines/add-pipeline-step.md
- docs/pipelines/add-pipeline.md
- docs/pipelines/edit-pipeline.md
- docs/pipelines/remove-pipeline-step.md
Includes disclaimer on posts related to configuration files and pipelines, that changes will only take effect after a new deployment.
The only post kept without changes was the "remove a pipeline".
Disclaimer text inspired by the message from the web app.
"Add a Configuration File" post preview with updated last step
[DVN-10902]: https://devopness.atlassian.net/browse/DVN-10902?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DVN-10903]: https://devopness.atlassian.net/browse/DVN-10903?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DVN-10904]: https://devopness.atlassian.net/browse/DVN-10904?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> docs: add disclaimer that changes will only take effect on next deployment

- docs/webhooks/create-incoming-webhook.md
Fixes name length input error on webhook creation, replacing for a more semantic option
N/A
> docs: update create-incoming-webhook.md

- docs/servers/ssh-into-server.md
- docs/ssh-keys/create-ssh-key-pair.md
- docs/users/find-your-activity-summary.md
- docs/webhooks/create-incoming-webhook.md
Replaces "In a terminal window" by "On your local machine, in a terminal window".
Changes were made programmatically using the command below
```shell
find ./docs -type f -exec sed -i 's/In a terminal window/On your local machine, in a terminal window/g' {} \;
```
N/A
> docs: clarify to open a terminal window on your local machine

- docs/cloud-provider-credentials/add-gcp-credential.md
> docs: insert "o" to google

- docs/cloud-provider-credentials/add-gcp-credential.md
Fixed a typo
N/A
https://www.devopness.com/docs/cloud-provider-credentials/add-gcp-credential/
> docs: update add-gcp-credential.md

- docs/applications/deploy-application-using-incoming-hook.md
Fix ordered list count reset on post steps
N/A
The fourth step restarts count: 1,2,3,1,2, ...
> docs: fix list numbering break on "deploy app using incoming hook" post

- docs/environments/add-teams-to-environment.md
- docs/roles/check-role-permissions.md
Adds a post guiding the user to inspect the role's permissions.
Post Preview "Check a Role's Permissions"
Update post notes on "Add team to an Environment" post
[DVN-11073]: https://devopness.atlassian.net/browse/DVN-11073?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DVN-11074]: https://devopness.atlassian.net/browse/DVN-11074?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DVN-11079]: https://devopness.atlassian.net/browse/DVN-11079?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DVN-11080]: https://devopness.atlassian.net/browse/DVN-11080?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> docs: add "Check a Role's Permissions" post

- docs/applications/add-ssl-certificate.md
- docs/roles/add-role.md
- docs/teams/add-team.md
Removes the "Add a Role" step from the introduction guide, as there will be roles created by default.
[DVN-11075]: https://devopness.atlassian.net/browse/DVN-11075?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DVN-11076]: https://devopness.atlassian.net/browse/DVN-11076?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DVN-11077]: https://devopness.atlassian.net/browse/DVN-11077?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DVN-11078]: https://devopness.atlassian.net/browse/DVN-11078?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> docs: remove links to "add a role" post

- docs/environments/archive-environment.md
- docs/servers/add-existing-server.md
- docs/servers/stop-server.md
Adds note tags to highlight notes in the rendered posts view
Note preview in post "DRAFT: Archive an Environment"
[DVN-11049]: https://devopness.atlassian.net/browse/DVN-11049?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DVN-11050]: https://devopness.atlassian.net/browse/DVN-11050?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DVN-11051]: https://devopness.atlassian.net/browse/DVN-11051?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> docs: add note callouts

- docs/applications/deploy-application.md
- docs/applications/link-server-to-application.md
- docs/configuration-files/add-configuration-file.md
Add post "Link a Server to an Application", guiding the user to link the application to a server before deploying.
Post Preview
[DVN-10980]: https://devopness.atlassian.net/browse/DVN-10980?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DVN-10780]: https://devopness.atlassian.net/browse/DVN-10780?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DVN-10828]: https://devopness.atlassian.net/browse/DVN-10828?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> docs: add "Link a Server to an Application" post

- packages/sdks/javascript/src/services/PipelineService.ts
Add `actions` property to `PipelineService` class
> feat: add 'actions' to 'PipelineService'

- packages/sdks/javascript/src/api/generated/models/application-environment-create.ts
- packages/sdks/javascript/src/api/generated/models/application-update.ts
- packages/sdks/javascript/src/api/spec.json
> feat: 2023-06-30 09:53 - Update API specification 

- packages/sdks/javascript/src/api/generated/models/action-pipeline-create.ts
- packages/sdks/javascript/src/api/spec.json
> feat: 2023-06-30 18:31 - Update API specification   

- packages/sdks/javascript/src/api/generated/models/network-rule-environment-create.ts
- packages/sdks/javascript/src/api/generated/models/network-rule-update.ts
- packages/sdks/javascript/src/api/generated/models/service-environment-create.ts
- packages/sdks/javascript/src/api/generated/models/service-reload.ts
- packages/sdks/javascript/src/api/generated/models/service-restart.ts
- packages/sdks/javascript/src/api/generated/models/service-start.ts
- packages/sdks/javascript/src/api/generated/models/service-stop.ts
- packages/sdks/javascript/src/api/generated/models/service-update-status.ts
- packages/sdks/javascript/src/api/generated/models/service-update.ts
- packages/sdks/javascript/src/api/generated/models/ssh-key-environment-create.ts
- packages/sdks/javascript/src/api/generated/models/ssh-key-update.ts
- packages/sdks/javascript/src/api/spec.json
> feat: 2023-07-09 23:14 -  Update API specification

- docs/pipelines/add-pipeline.md
- docs/servers/add-aws-server.md
- docs/servers/add-digitalocean-server.md
- docs/servers/add-gcp-server.md
- docs/servers/index.md
Includes generic step to follow the form prompts, allowing the app to grow while maintaining the documentation updated.
[DVN-11327]: https://devopness.atlassian.net/browse/DVN-11327?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DVN-11326]: https://devopness.atlassian.net/browse/DVN-11326?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DVN-11329]: https://devopness.atlassian.net/browse/DVN-11329?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DVN-11328]: https://devopness.atlassian.net/browse/DVN-11328?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DVN-11330]: …
> docs: add "follow the prompts" step to servers and pipeline posts

- packages/sdks/javascript/src/api/generated/apis/pipelines-actions-api.ts
- packages/sdks/javascript/src/api/generated/models/action-relation.ts
- packages/sdks/javascript/src/api/generated/models/action-retry-response.ts
- packages/sdks/javascript/src/api/generated/models/action-type.ts
- packages/sdks/javascript/src/api/generated/models/action.ts
- packages/sdks/javascript/src/api/generated/models/cloud-provider-service-code.ts
- packages/sdks/javascript/src/api/generated/models/server-update.ts
- packages/sdks/javascript/src/api/spec.json
> feat: 2023-07-17 21:39 - Update API specification 

- docs/applications/add-application.md
- docs/applications/add-ssl-certificate.md
- docs/applications/deploy-application.md
- docs/configuration-files/add-configuration-file.md
- docs/configuration-files/edit-configuration-file.md
- docs/configuration-files/remove-configuration-file.md
- docs/pipelines/add-pipeline-step.md
- docs/pipelines/add-pipeline.md
- docs/pipelines/edit-pipeline.md
- docs/pipelines/remove-pipeline-step.md
- docs/pipelines/remove-pipeline.md
- docs/servers/add-existing-server.md
- docs/servers/check-server-provision-logs.md
- docs/servers/find-server-ip-address.md
Adds required permission information to posts from:
- Applications
- Configuration Files
- Pipelines
- Servers
[DVN-11380]: https://devopness.atlassian.net/browse/DVN-11380?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DVN-11385]: https://devopness.atlassian.net/browse/DVN-11385?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DVN-11386]: https://devopness.atlassian.net/browse/DVN-11386?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DVN-11387]: https://devopness.atlassian.net/browse/DVN-11387?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DVN-11381]: …
> docs: add required permissions information to some posts

- packages/sdks/javascript/src/api/generated/models/action-pipeline-create.ts
- packages/sdks/javascript/src/api/spec.json
> feat: 2023-07-25 22:13 - Update API specification   

- docs/applications/deploy-application.md
- docs/environments/add-environment.md
- docs/environments/archive-environment.md
- docs/environments/find-archived-environment.md
- docs/environments/list-environments.md
- docs/environments/unarchive-environment.md
- docs/servers/add-aws-server.md
- docs/servers/add-digitalocean-server.md
- docs/servers/add-existing-server.md
- docs/servers/add-gcp-server.md
- docs/servers/add-server.md
- docs/servers/check-server-provision-logs.md
- docs/servers/get-server-status.md
- docs/servers/index.md
- docs/servers/remove-server.md
- docs/servers/restart-server.md
- docs/servers/start-server.md
- docs/servers/stop-server.md
- docs/users/credentials/add-credential.md
- docs/users/credentials/index.md
- Update posts that document routes in the web app with multiple options, e.g
1. Add a Server
2. Add a Credential
3. List Environments
- Removes draft flag from posts related to features already in production.
- Updates the getting started guide link from `docs/servers/index.md` to `docs/servers/add-server.md`
> docs: update posts with multiple options in app

- packages/sdks/javascript/src/api/generated/apis/pipelines-hooks-api.ts
- packages/sdks/javascript/src/api/spec.json
> feat: 2023-08-22 18:03 - Update API specification

- packages/sdks/javascript/src/services/PipelineService.ts
> fix: expose pipeline hooks in PipelineServices

- packages/sdks/javascript/src/api/generated/models/action-resource.ts
- packages/sdks/javascript/src/api/generated/models/environment.ts
- packages/sdks/javascript/src/api/spec.json
> feat: 2023-08-24 11:26 -  Update API specification

- packages/sdks/javascript/src/api/generated/models/action-target-data.ts
- packages/sdks/javascript/src/api/generated/models/action-target-network-data.ts
- packages/sdks/javascript/src/api/generated/models/network-relation.ts
- packages/sdks/javascript/src/api/generated/models/network.ts
- packages/sdks/javascript/src/api/spec.json
> feat: 2023-08-24 19:08 - Update API specification 

- docs/files/remove-file.md
- docs/pipelines/remove-pipeline.md
- docs/pipelines/steps/remove-step.md
- docs/servers/remove-server.md
- docs/ssh-keys/remove-ssh-key.md
- docs/users/credentials/remove-credential.md
1. Simplify intro to remove resource posts:
- Reduce number of assumptions about user situation
- Less information for the user to digest
- Straight to the point
1. Update instructions:
- Use updated instructions patterns, e.g "Follow the prompts"
- Highlight commands using commands to split the action and why/consequence of executing
- Final step updated with a way to verify the instructions have been completed successfully, e.g "the recently removed `File` will be gone"
N/A
> docs: update writing in "remove resource" posts

- docs/subnets/index.md
- docs/subnets/remove-subnet.md
1. Creates "Introduction" article to Subnet section
1. Creates "Remove a subnet" article
Post preview: Remove a Subnet
Post preview: Introduction
[DVN-11827]: https://devopness.atlassian.net/browse/DVN-11827?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DVN-11828]: https://devopness.atlassian.net/browse/DVN-11828?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> docs: create "remove a subnet" article

- packages/sdks/javascript/src/api/generated/models/hook-pipeline-create.ts
- packages/sdks/javascript/src/api/spec.json
> feat: 2023-09-05 23:04 - Update API specification   

- packages/sdks/javascript/src/api/generated/models/subnet-provision-input-settings-gcp.ts
- packages/sdks/javascript/src/api/generated/models/subnet-type.ts
- packages/sdks/javascript/src/api/spec.json
> feat: 2023-09-08 14:51 - Update API specification 

- packages/sdks/javascript/src/api/generated/models/cloud-provider-service-resource-type.ts
- packages/sdks/javascript/src/api/generated/models/cloud-provider-service.ts
- packages/sdks/javascript/src/api/spec.json
> feat: 2023-09-09 11:53 -  Update API specification

- packages/sdks/javascript/src/api/generated/models/action-resource.ts
- packages/sdks/javascript/src/api/spec.json
> feat: 2023-09-12 12:09 -  Update API specification

- packages/sdks/javascript/src/api/generated/models/pipeline-create.ts
- packages/sdks/javascript/src/api/generated/models/pipeline-update.ts
- packages/sdks/javascript/src/api/generated/models/server-environment-create.ts
- packages/sdks/javascript/src/api/generated/models/server-update.ts
- packages/sdks/javascript/src/api/spec.json
> feat: 2023-09-21 16:07 - Update API specification  

- packages/sdks/javascript/src/api/generated/apis/actions-api.ts
- packages/sdks/javascript/src/api/spec.json
> feat: 2023-09-25 20:56 - Update API specification 

- packages/sdks/javascript/src/api/generated/apis/environments-networks-api.ts
- packages/sdks/javascript/src/api/generated/apis/networks-subnets-api.ts
- packages/sdks/javascript/src/api/generated/models/network-environment-create.ts
- packages/sdks/javascript/src/api/generated/models/network-provision-input.ts
- packages/sdks/javascript/src/api/generated/models/network-relation.ts
- packages/sdks/javascript/src/api/generated/models/subnet-provision-input-settings-digital-ocean.ts
- packages/sdks/javascript/src/api/spec.json
> feat: 2023-09-29 01:21 - Update API specification 

- packages/sdks/javascript/src/api/generated/apis/environments-actions-api.ts
- packages/sdks/javascript/src/api/spec.json
> feat: 2023-09-29 14:08 - Update API specification  

- docs/applications/deploy-application.md
Update required permission section with the operation deploy instead of pipeline_run
N/A
> docs: replace `pipeline_run` with `deploy`

- packages/sdks/javascript/src/api/generated/apis/static-data-cloud-provider-service-instances-api.ts
- packages/sdks/javascript/src/api/generated/models/archived-environment-relation.ts
- packages/sdks/javascript/src/api/generated/models/environment-relation.ts
- packages/sdks/javascript/src/api/generated/models/user-billing.ts
- packages/sdks/javascript/src/api/spec.json
> feat: 2023-10-02 20:39 - Update API specification  

- packages/sdks/javascript/src/api/generated/apis/actions-api.ts
- packages/sdks/javascript/src/api/spec.json
[DVN-12243]: https://devopness.atlassian.net/browse/DVN-12243?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: force  CI to SDK release

- packages/sdks/javascript/src/api/generated/apis/actions-api.ts
- packages/sdks/javascript/src/api/generated/models/service-type.ts
- packages/sdks/javascript/src/api/spec.json
> feat: 2023-10-10 17:28 - Update API specification  

- docs/users/subscriptions/faq/index.md
Removes hardcoded links (`https://devopness.com/...`) and placeholders (`http://link-a-ser-definido.com`), replacing for relative paths and a # where links still need to be created.
https://thlmenezes-site.devopness.com/docs/users/subscriptions/faq/
Now the urls preserve the site instance, instead of always redirecting to https://www.devopness.com
[DVN-12616]: https://devopness.atlassian.net/browse/DVN-12616?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: remove hardcoded urls, using relative paths instead

- docs/applications/deploy-application-using-incoming-hook.md
- docs/applications/integrate-application-deployments-to-ci-workflows.md
- docs/webhooks/create-incoming-webhook.md
- docs/webhooks/create-outgoing-webhook.md
Update webhook related posts to use new API endpoint
[DVN-11551]: https://devopness.atlassian.net/browse/DVN-11551?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> docs: update webhook related instructions

- docs/servers/index.md
- docs/servers/start-server.md
- docs/servers/view-server.md
1. Update Server Introduction post
1. Add links to all posts, except server actions related
1. Add "View a Server" post [1]
1. Add links to all server actions
[1] Adding the server action links here, the post will show up in the server details page
Post preview: server introduction
Post preview: view a server
[DVN-12576]: https://devopness.atlassian.net/browse/DVN-12576?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DVN-12577]: https://devopness.atlassian.net/browse/DVN-12577?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DVN-12578]: https://devopness.atlassian.net/browse/DVN-12578?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: add links to server posts

- docs/linked-resources/add-linked-resource.md
- docs/network-rules/add-network-rule.md
- docs/network-rules/index.md
- docs/pipelines/run-pipeline.md
- docs/servers/start-server.md
1. Creates Network Rules Introduction post
1. Creates "Add a Network Rule" post
1. Creates "Run a Pipeline" post
1. Add note to "Add a Linked Resource" post
[DVN-12274]: https://devopness.atlassian.net/browse/DVN-12274?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DVN-12275]: https://devopness.atlassian.net/browse/DVN-12275?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DVN-12276]: https://devopness.atlassian.net/browse/DVN-12276?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DVN-12277]: https://devopness.atlassian.net/browse/DVN-12277?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: create "add network rule" post

- docs/servers/add-existing-server.md
- docs/servers/delete-cloudprovider-server.md
- docs/servers/remove-selfhosted-server.md
- docs/servers/remove-server.md
Updates remove a server post to guide users removing self hosted servers, outlining the differences with deleting a devopness provisioned server on a cloud provider (e.g aws, digitalocean, gcp)
[DVN-12580]: https://devopness.atlassian.net/browse/DVN-12580?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DVN-12581]: https://devopness.atlassian.net/browse/DVN-12581?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: update server remove post

- docs/users/subscriptions/index.md
Add docs about billing, billing settings, credits and usage limits.
[DVN-12215]: https://devopness.atlassian.net/browse/DVN-12215?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> docs: add info about billing and credits

- packages/sdks/javascript/src/api/generated/models/network-provision-input.ts
- packages/sdks/javascript/src/api/generated/models/server.ts
- packages/sdks/javascript/src/api/spec.json
> feat: 2023-10-26 20:27 - Update API specification

- docs/applications/edit-application.md
1. Creates draft post "Edit an Application"
Post Preview
[DVN-12672]: https://devopness.atlassian.net/browse/DVN-12672?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DVN-12673]: https://devopness.atlassian.net/browse/DVN-12673?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: add "edit an application" post

- packages/sdks/javascript/src/api/generated/models/cloud-provider-relation.ts
- packages/sdks/javascript/src/api/generated/models/cloud-provider-service-region.ts
- packages/sdks/javascript/src/api/generated/models/cloud-provider.ts
- packages/sdks/javascript/src/api/generated/models/index.ts
- packages/sdks/javascript/src/api/generated/models/network-rule-options.ts
- packages/sdks/javascript/src/api/generated/models/operating-system.ts
- packages/sdks/javascript/src/api/generated/models/pipeline-settings-stage.ts
- packages/sdks/javascript/src/api/generated/models/pipeline-settings-variable.ts
- packages/sdks/javascript/src/api/generated/models/script-runner.ts
- packages/sdks/javascript/src/api/generated/models/static-cron-job-frequency.ts
- packages/sdks/javascript/src/api/generated/models/static-environment-type.ts
- packages/sdks/javascript/src/api/generated/models/static-network-rule-direction.ts
- packages/sdks/javascript/src/api/generated/models/static-permission.ts
- packages/sdks/javascript/src/api/generated/models/static-service-type.ts
- packages/sdks/javascript/src/api/generated/models/variable-targets.ts
- packages/sdks/javascript/src/api/spec.json
> feat: 2023-10-27 19:36 - Update API specification

- packages/sdks/javascript/src/api/generated/models/service-type.ts
- packages/sdks/javascript/src/api/spec.json
> feat: 2023-10-29 14:31 - Update API specification  

- packages/sdks/javascript/src/api/generated/models/application-environment-create.ts
- packages/sdks/javascript/src/api/generated/models/application-update.ts
- packages/sdks/javascript/src/api/spec.json
> feat: 2023-11-07 00:52 - Update API specification

- packages/sdks/javascript/src/api/generated/models/action-pipeline-create.ts
- packages/sdks/javascript/src/api/generated/models/application-environment-create.ts
- packages/sdks/javascript/src/api/generated/models/application-update.ts
- packages/sdks/javascript/src/api/generated/models/deployment-application-create.ts
- packages/sdks/javascript/src/api/generated/models/service-environment-create.ts
- packages/sdks/javascript/src/api/spec.json
> feat: 2023-11-08 15:39 - Update API specification  

- packages/sdks/javascript/src/api/generated/models/action-pipeline-create.ts
- packages/sdks/javascript/src/api/generated/models/deployment-application-create.ts
- packages/sdks/javascript/src/api/spec.json
> feat: 2023-11-16 14:40 - Update API specification  

- packages/sdks/javascript/src/api/generated/models/action-deployment-commit.ts
- packages/sdks/javascript/src/api/generated/models/action-deployment-content.ts
- packages/sdks/javascript/src/api/generated/models/index.ts
- packages/sdks/javascript/src/api/generated/models/repository-tag-commit.ts
- packages/sdks/javascript/src/api/spec.json
> feat: 2023-11-19 20:58 -  Update API specification

- packages/sdks/javascript/README.md
This PR fixes the incorrect method used in the README.md example on how to use the SDK.
N/A.
> fix: use correct method to get current user

- .github/ISSUE_TEMPLATE/feature_request.yml
The new form template had errors that only became apparent after merging. This PR corrects those errors.
[DVN-13021]: https://devopness.atlassian.net/browse/DVN-13021?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: fix errors on issue template for feature requests

- .github/ISSUE_TEMPLATE/bug_report.yml
The bug report form template also had an error that had not become apparent until it was merged. This PR fixes it.
[DVN-13018]: https://devopness.atlassian.net/browse/DVN-13018?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: fix identation of description text

- packages/sdks/javascript/src/api/generated/models/application-environment-create.ts
- packages/sdks/javascript/src/api/generated/models/application-update.ts
- packages/sdks/javascript/src/api/spec.json
> feat: 2023-12-04 19:43 - Update API specification

- .github/workflows/sdk-javascript-release.yml
There was a mistake with the declared path to the `src` directory in the `sdk-javascript-release.yml` which was made clear after this Pull Request: https://github.com/devopness/devopness/pull/813 failed to trigger a new release. This PR is meant to fix that mistake.
[DVN-13106]: https://devopness.atlassian.net/browse/DVN-13106?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: fix src path to properly include changes to any files within

- packages/sdks/javascript/src/api/generated/models/variable-targets.ts
- packages/sdks/javascript/src/api/spec.json
> feat: 2023-12-07 12:57 - Update API specification  

- packages/sdks/javascript/src/services/StaticService.ts
- Add `serverOptions` property to `StaticService`
> fix: add 'serverOptions' to 'StaticService'

- .github/ISSUE_TEMPLATE/bug_report.yml
- .github/SECURITY.md
- docs/security/index.md
- docs/security/reporting-a-security-vulnerability.md
This PR adds a security policy to the repository with instructions to refer someone who wants to report a security vulnerability to our documentation as well as the mentioned documentation on how and where to report a security vulnerability itself.
[DVN-13097]: https://devopness.atlassian.net/browse/DVN-13097?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DVN-13101]: https://devopness.atlassian.net/browse/DVN-13101?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: add security policy for vulnerability disclosure

- packages/sdks/javascript/src/api/generated/models/action-relation.ts
- packages/sdks/javascript/src/api/generated/models/action-retry-response.ts
- packages/sdks/javascript/src/api/generated/models/action.ts
- packages/sdks/javascript/src/api/generated/models/application-environment-create.ts
- packages/sdks/javascript/src/api/generated/models/application-update.ts
- packages/sdks/javascript/src/api/spec.json
> feat: 2023-12-13 00:05 - Update API specification  

- packages/sdks/javascript/src/api/spec.json
> docs: 2023-12-14 18:45 - Update API specification

- docs/index.md
- Updates "Introduction to Devopness" doc article
- Add "docs/index.md" file to this repo
- N/A
- Once the changes in this PR are merged and deployed, success criteria is: Update the article https://www.devopness.com/docs/
BEFORE:
AFTER:
[DVN-13037]: https://devopness.atlassian.net/browse/DVN-13037?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> docs: update home/introduction to docs article

- docs/servers/add-server.md
- Add next link to "Add Server" post
- N/A
- Once the changes in this PR are merged and deployed, success criteria is: update Add Server post with next link
> docs: update next link add-server.md

- .github/ISSUE_TEMPLATE/bug_report.yml
This PR: 
- Reorders the input fields for a better experience when reporting a bug.
- Changes the first line of the warning text to guide the user to the repository's security advisory report form.
N/A.
> refactor: modify and reorganize bug report form

- packages/sdks/javascript/src/api/generated/models/hook-update.ts
- packages/sdks/javascript/src/api/spec.json
> feat: 2023-12-23 01:27 - Update API specification  

- docs/applications/deploy-application.md
- docs/webhooks/create-incoming-webhook.md
- docs/webhooks/create-outgoing-webhook.md
- Update articles to reflect changes from deploy branch only to deploying source_type/source_ref
- Add commit link to outgoing hook message, to differentiate which comment refers to which deployment
- N/A
- Once the changes in this PR are merged and deployed, success criteria is: No article mentioning param branch on deploy form
> docs: update deploy/hook articles to use source_type/source_ref

- .github/DISCUSSION_TEMPLATE/ideas-feature-requests.yml
- .github/ISSUE_TEMPLATE/bug_report.yml
- .github/ISSUE_TEMPLATE/config.yml
- .github/labeler-issue.yml
- .github/labeler-pr.yml
- .github/workflows/issue-stale.yml
- Once the changes in this PR are merged and deployed, success criteria is: Feature requests will be moved to the repository's discussions page.
[DVN-13404]: https://devopness.atlassian.net/browse/DVN-13404?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DVN-13421]: https://devopness.atlassian.net/browse/DVN-13421?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DVN-13428]: https://devopness.atlassian.net/browse/DVN-13428?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> refactor: update issue tags and add discussion form

- .github/config.yml
- Configures [Welcome bot](https://github.com/apps/welcome)
- N/A
- Once the changes in this PR are merged and deployed, success criteria is: A automated message is sent for every first issue open, PR open and PR merged for each user
https://probot.github.io/apps/welcome/
> chore: configure welcome-bot

- docs/index.md
N/A
- Once the changes in this PR are merged and deployed, success criteria is: link should correctly point to this repo `Discussions` page
> fix: link to GitHub Discussions

- docs/applications/edit-application.md
- docs/files/edit-file.md
- docs/files/remove-file.md
- docs/linked-resources/add-linked-resource.md
- docs/networks/remove-network.md
- docs/pipelines/edit-pipeline.md
- docs/pipelines/remove-pipeline.md
- docs/servers/delete-cloudprovider-server.md
- docs/servers/remove-selfhosted-server.md
- docs/ssh-keys/link-ssh-key.md
- docs/subnets/remove-subnet.md
Hi!
In this PR, details were corrected in some topics in the documentation.
This PR solves #848
> fix: Updating topics in documentation

- docs/users/credentials/add-gcp-credential.md
N/A
- Once the changes in this PR are merged and deployed, success criteria is: a credential created following this article should have all the requirements for server provision enabled
Server [provision failed](https://app.devopness.com/actions/21900) because this API wasn't enabled.
> docs: Add Cloud Asset API activation requirement

- docs/pipelines/add-pipeline.md
- Once the changes in this PR are merged and deployed, success criteria is: Update the article [https://www.devopness.com/docs/pipelines/add-pipeline/](https://www.devopness.com/docs/pipelines/add-pipeline/)
> docs: update pipelines/add-pipeline article to add warning about `CUSTOM` operation

- packages/sdks/javascript/src/DevopnessApiClient.ts
Order services in `DevopnessApiClient`. This PR also aims to generate a new release of the JS SDK.
N/A
- Once the changes in this PR are merged and deployed, success criteria is: New JS SDK version generated successfully
N/A
> feat: order services in DevopnessApiClient

- packages/sdks/javascript/src/api/generated/models/application-environment-create.ts
- packages/sdks/javascript/src/api/generated/models/application-relation.ts
- packages/sdks/javascript/src/api/generated/models/application-update.ts
- packages/sdks/javascript/src/api/generated/models/application.ts
- packages/sdks/javascript/src/api/generated/models/language-runtime-framework-defaults.ts
- packages/sdks/javascript/src/api/generated/models/trigger-event.ts
- packages/sdks/javascript/src/api/spec.json
> feat: 2024-03-02 01:36 - Update API specification  

- packages/sdks/javascript/src/api/generated/models/application-environment-create.ts
- packages/sdks/javascript/src/api/generated/models/application-relation.ts
- packages/sdks/javascript/src/api/generated/models/application-update.ts
- packages/sdks/javascript/src/api/generated/models/application.ts
- packages/sdks/javascript/src/api/generated/models/language-runtime-framework-defaults.ts
- packages/sdks/javascript/src/api/spec.json
> feat: 2024-03-04 12:02 - Update API specification 

- docs/environments/archive-environment.md
- docs/environments/unarchive-environment.md
This commit addresses the "Archive/Unarchive an Environment" issue by updating the documentation.
- Add clear instructions for the users who wants to archiving/unarchiving environments.
> docs: fix articles archive/unarchive an environment (#884) 

- packages/sdks/javascript/src/api/generated/models/application-relation.ts
- packages/sdks/javascript/src/api/generated/models/application.ts
- packages/sdks/javascript/src/api/spec.json
> feat: 2024-03-13 02:12 - Update API specification 

- packages/sdks/javascript/src/api/generated/models/source-provider-options-relation.ts
- packages/sdks/javascript/src/api/spec.json
> feat: 2024-03-16 20:30 - Update API specification 

- packages/sdks/javascript/src/api/spec.json
> feat: 2024-03-22 14:24 - Update API specification

- docs/ssh-keys/remove-ssh-key.md
- Once the changes in this PR are merged and deployed, success criteria is:  Update the article https://www.devopness.com/docs/ssh-keys/remove-ssh-key/
> docs: fix article "Remove an SSH Key" to guide the user to click resource name

- docs/files/remove-file.md
- Once the changes in this PR are merged and deployed, success criteria is: Update the article https://www.devopness.com/docs/files/remove-file/
> docs: fix article "Remove a File" to guide the user to click resource name and to use the tabs

- LICENSE
> fix: copyright year

- CODE_OF_CONDUCT.md
> chore: update CODE_OF_CONDUCT

- packages/sdks/javascript/src/api/generated/apis/virtual-hosts-api.ts
- packages/sdks/javascript/src/api/generated/models/index.ts
- packages/sdks/javascript/src/api/generated/models/linked-resource-attribute.ts
- packages/sdks/javascript/src/api/generated/models/virtual-host-relation.ts
- packages/sdks/javascript/src/api/generated/models/virtual-host-update.ts
- packages/sdks/javascript/src/api/generated/models/virtual-host.ts
- packages/sdks/javascript/src/api/spec.json
> feat: 2024-04-01 20:31 - Update API specification   

- docs/roles/view-role.md
- Once the changes in this PR are merged and deployed, success criteria is: Update the article https://www.devopness.com/docs/roles/view-role/
> docs: fix article "Check a Role's Permissions" to guide the user to click resource name

- docs/pipelines/edit-pipeline.md
- Once the changes in this PR are merged and deployed, success criteria is: Update the article https://www.devopness.com/docs/pipelines/edit-pipeline/
> docs: fix article "Edit a Pipeline" to guide the user to click resource name and to use the tabs

- docs/pipelines/remove-pipeline.md
- Once the changes in this PR are merged and deployed, success criteria is: Update the article https://www.devopness.com/docs/pipelines/remove-pipeline/
> docs: fix article "Remove a Pipeline" to guide the user to click resource name and to use the tabs

- docs/applications/deploy-application-using-incoming-hook.md
- Once the changes in this PR are merged and deployed, success criteria is: Update the article https://www.devopness.com/docs/applications/deploy-application-using-incoming-hook/
> docs: fix article "Deploy Application using an Incoming Hook" to guide the user to click resource name and and the tabs

- docs/ssh-keys/deploy-ssh-key.md
- Once the changes in this PR are merged and deployed, success criteria is: Update the article https://www.devopness.com/docs/ssh-keys/deploy-ssh-key/
> docs: fix article "Deploy SSH Key" to guide the user to click resource name

- docs/ssl-certificates/add-ssl-certificate.md
- Once the changes in this PR are merged and deployed, success criteria is: Update the article https://www.devopness.com/docs/ssl-certificates/add-ssl-certificate/
> docs: fix article "Add an SSL Certificate" to guide user to click resource name

- docs/servers/start-server.md
- Once the changes in this PR are merged and deployed, success criteria is: Update the article https://www.devopness.com/docs/servers/start-server/
> docs: fix article "Start a Server" to guide the user to click resource name

- docs/servers/remove-selfhosted-server.md
- Once the changes in this PR are merged and deployed, success criteria is: Update the article https://www.devopness.com/docs/servers/remove-selfhosted-server/
> docs: fix article "Remove a Self Hosted Server" to guide the user to click resource  name

- docs/servers/get-server-status.md
- Once the changes in this PR are merged and deployed, success criteria is: Update the article https://www.devopness.com/docs/servers/get-server-status/
> docs: fix article "Get a Server’s Status" to guide the user to click resource name and to use the  tabs

- docs/pipelines/steps/add-step.md
- Once the changes in this PR are merged and deployed, success criteria is: Update the article https://www.devopness.com/docs/pipelines/steps/add-step/
> docs: fix article "Add Step to Pipeline " to guide the user to click resource name and to use the  tabs

- docs/pipelines/steps/remove-step.md
- Once the changes in this PR are merged and deployed, success criteria is: Update the article https://www.devopness.com/docs/pipelines/steps/remove-step/
> docs: fix article "Remove Step from Pipeline" to guide the user to click resource name and to use the tabs

- docs/pipelines/run-pipeline.md
- Once the changes in this PR are merged and deployed, success criteria is: Update the article https://www.devopness.com/docs/pipelines/run-pipeline/
> docs: fix article "Run a Pipeline" to guide the user to click resource name and to use the tabs

- docs/servers/restart-server.md
- Once the changes in this PR are merged and deployed, success criteria is: Update the article https://www.devopness.com/docs/servers/restart-server/
> docs: fix article "Restart a Server" to guide the user to click resource name

- docs/servers/stop-server.md
- Once the changes in this PR are merged and deployed, success criteria is: Update the article https://www.devopness.com/docs/servers/stop-server/
> docs: fix article "Stop a Server" to guide the user to click resource name

- docs/virtual-hosts/add-virtual-host.md
- docs/virtual-hosts/edit-virtual-host.md
- docs/virtual-hosts/index.md
Added articles describing how to add and edit a virtual host
N/A
- Once the changes in this PR are merged and deployed, success criteria is: The virtual host creation and edition steps on the documentation should reflect the current UX of Devopness
> docs: add virtual hosts articles ADD and EDIT

- .github/config.yml
- Update welcome bot first PR message to mention contributing guidelines
N/A
- Once the changes in this PR are merged and deployed, success criteria is: Welcome bot should point users to read contributing guidelines
> feat: update first PR bot message to mention contributing guidelines

- .github/workflows/cla.yml
- Adds CLA Assistant to validate CLA signatures
N/A
- Once the changes in this PR are merged and deployed, success criteria is: Contributors will be guided to read and sign Devopness CLA
[DVN-14548]
[DVN-14406]
[DVN-14548]: https://devopness.atlassian.net/browse/DVN-14548?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DVN-14406]: https://devopness.atlassian.net/browse/DVN-14406
> feat: add cla assistant to repo

- .github/workflows/cla-assistant.yml
- .github/workflows/cla.yml
- Move to public repository the reusable workflow to validate CLA signatures
N/A
- Once the changes in this PR are merged and deployed, success criteria is: Should fix "workflow not found" error
> fix: cla assistant action not triggering

- packages/sdks/javascript/src/api/generated/models/application-environment-create.ts
- packages/sdks/javascript/src/api/generated/models/application-relation.ts
- packages/sdks/javascript/src/api/generated/models/application-update.ts
- packages/sdks/javascript/src/api/generated/models/application.ts
- packages/sdks/javascript/src/api/spec.json
> feat: 2024-05-23 02:26 - Update API specification 

- packages/sdks/javascript/src/api/generated/models/operating-system-version.ts
- packages/sdks/javascript/src/api/generated/models/server.ts
- packages/sdks/javascript/src/api/spec.json
> feat: 2024-07-10 17:45 - Update API specification 

- packages/sdks/javascript/src/api/generated/models/daemon-relation.ts
- packages/sdks/javascript/src/api/generated/models/daemon.ts
- packages/sdks/javascript/src/api/spec.json
> feat: 2024-07-18 20:32 - Update API specification 

- .github/workflows/sdk-javascript-ci.yml
- .github/workflows/sdk-javascript-release.yml
- packages/sdks/javascript/Dockerfile-dev
- packages/sdks/javascript/Makefile
- packages/sdks/javascript/package-lock.json
- packages/sdks/javascript/package.json
- Once the changes in this PR are merged and deployed, success criteria is: SDK will be built using node 20 and latest dev dependencies
> build(deps): update node, jest and dev dependencies

- docs/applications/deploy-application.md
- docs/ssl-certificates/add-ssl-certificate.md
- docs/virtual-hosts/add-virtual-host.md
- The article 'Deploy application' has been updated to guide the user on creating a virtual host as the next step in their journey.
- A note was added to inform the user that they can create a virtual host in Devopness, for make the application publicly accessible over the internet.
- The article 'Add virtual host' has been updated to guide the user on creating an SSL certificate as the next step in their journey.
- A note was added explaining how to ensure a valid domain for a virtual host of type Domain name
- A note was added to inform the user that they can create an SSL certificate in Devopness, to make communication with the virtual host secure.
- Removed section on how to `configure a DNS record pointing to your servers` from the article 'Add SSL certificate'
- Simplified and moved …
> docs: update `Deploy application` article to guide the user to add a virtual host in next step 

- docs/files/index.md
N/A
- Once the changes in this PR are merged and deployed, success criteria is: The introduction to configuration files has been updated
N/A
> docs: change intro to configuration files

- docs/applications/deploy-application.md
- docs/virtual-hosts/add-virtual-host.md
- `Add Virtual host`: added note explaining what the user needs to ensure when creating an IP-based virtual host
- `Add Virtual host`: added **Deploy Application** as previous article
- `Deploy Application`: updated note to expose the reader to the possibility of testing the application using an IP-based virtual host
- Once the changes in this PR are merged and deployed, success criteria is: readers should be aware of the possibility of testing their applications by creating a virtual host for the server IP.
<details><summary>Add a Virtual host article</summary>
> ![image](https://github.com/user-attachments/assets/2e5f6ccc-841d-4edf-aa27-8dae165b4469)
</details> 
<details><summary>Deploy Application article</summary>
> ![image](https://github.com/user-attachments/assets/e9e86d6a-e95b-40b4 …
> docs: update `Add Virtual host` to note about virtual host ip based 

- docs/subnets/add-subnet.md
- Once the changes in this PR are merged and deployed, success criteria is: The reader of "Add a Subnet" article is correctly guided through the flow required to add a subnet.
[DVN-14747]: https://devopness.atlassian.net/browse/DVN-14747?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> docs: update `add subnet` article to guide the user to use the subnets tab

- packages/sdks/javascript/src/api/generated/models/cloud-provider-code.ts
- packages/sdks/javascript/src/api/generated/models/network-rule-environment-create.ts
- packages/sdks/javascript/src/api/generated/models/server-relation.ts
- packages/sdks/javascript/src/api/generated/models/virtual-host-update.ts
- packages/sdks/javascript/src/api/spec.json
> feat: 2024-09-17 23:59 - Update API Specification

- packages/sdks/javascript/src/api/generated/models/application-environment-create.ts
- packages/sdks/javascript/src/api/generated/models/application-update.ts
- packages/sdks/javascript/src/api/generated/models/credential-update.ts
- packages/sdks/javascript/src/api/generated/models/cron-job-environment-create.ts
- packages/sdks/javascript/src/api/generated/models/cron-job-update.ts
- packages/sdks/javascript/src/api/generated/models/daemon-environment-create.ts
- packages/sdks/javascript/src/api/generated/models/daemon-update.ts
- packages/sdks/javascript/src/api/generated/models/environment-update.ts
- packages/sdks/javascript/src/api/generated/models/hook-update.ts
- packages/sdks/javascript/src/api/generated/models/index.ts
- packages/sdks/javascript/src/api/generated/models/network-rule-environment-create.ts
- packages/sdks/javascript/src/api/generated/models/network-rule-update.ts
- packages/sdks/javascript/src/api/generated/models/network-update.ts
- packages/sdks/javascript/src/api/generated/models/pipeline-update.ts
- packages/sdks/javascript/src/api/generated/models/project-update.ts
- packages/sdks/javascript/src/api/generated/models/resource-to-be-linked.ts
- packages/sdks/javascript/src/api/generated/models/role-update.ts
- packages/sdks/javascript/src/api/generated/models/server-update.ts
- packages/sdks/javascript/src/api/generated/models/service-environment-create.ts
- packages/sdks/javascript/src/api/generated/models/ssh-key-environment-create.ts
- packages/sdks/javascript/src/api/generated/models/ssh-key-update.ts
- packages/sdks/javascript/src/api/generated/models/step-pipeline-update.ts
- packages/sdks/javascript/src/api/generated/models/team-update.ts
- packages/sdks/javascript/src/api/generated/models/user-update.ts
- packages/sdks/javascript/src/api/generated/models/variable-update.ts
- packages/sdks/javascript/src/api/generated/models/virtual-host-environment-create.ts
- packages/sdks/javascript/src/api/generated/models/virtual-host-update.ts
- packages/sdks/javascript/src/api/spec.json
> feat: 2024-09-25 20:56 - Update API specification 

- .github/workflows/ui-react-ci.yml
- .github/workflows/ui-react-release.yml
- packages/ui/react/package.json
- Publish new releases of @devopness/ui-react to npm
- Run CI on PRs related to package @devopness/ui-react
N/A
- New PRs changing packages/ui/react code should trigger CI Action
- New changes on packages/ui/react pushed to main should Release Action
The new workflow files were created using SDK-JS as base, the diffs below were generated to highlight the changes made and facilitate code review.
Diffs generated using the commands below
```
cd .github/workflows
git diff --no-index -- *-ci.yml
git diff --no-index -- *-release.yml
```
```diff
diff --git a/sdk-javascript-ci.yml b/ui-react-ci.yml
index 2591a31..866b66d 100755
--- a/sdk-javascript-ci.yml
+++ b/ui-react-ci.yml
@@ -1,16 +1,16 @@
-name: SDK JavaScript - CI …
```
> feat(design-system): publish UI components to npm

- packages/ui/react/package.json
- packages/ui/react/vite.config.ts
- Allow users to import @devopness/ui-react using CommonJS files
```ts
// ECMAScript import
import { Button } from '@devopness/ui-react'
// CommonJS import
const { Button } = require('@devopness/ui-react')
```
Currently, only ECMAScript imports are supported
N/A
- Once the changes in this PR are merged and deployed, success criteria is: Users using CommonJS modules can import @devopness/ui-react components
- [Modules: CommonJS modules](https://nodejs.org/api/modules.html#modules-commonjs-modules)
- [Modules: ECMAScript modules](https://nodejs.org/api/esm.html#modules-ecmascript-modules)
> feat(design-system): add support to CommonJS `require('@devopness/ui-react')`

- .changeset/add-Dropdown-component.md
- .changeset/add-Icon-component.md
- .changeset/add-Link-component.md
- .changeset/add-colors-get-opacity.md
- .changeset/fix-type-import-paths.md
- package-lock.json
- packages/ui/react/package.json
- packages/ui/react/src/colors/getColor.ts
- packages/ui/react/src/colors/index.ts
- packages/ui/react/src/colors/types.ts
- packages/ui/react/src/components/Primitives/Dropdown/Dropdown.stories.ts
- packages/ui/react/src/components/Primitives/Dropdown/Dropdown.styled.ts
- packages/ui/react/src/components/Primitives/Dropdown/Dropdown.test.tsx
- packages/ui/react/src/components/Primitives/Dropdown/Dropdown.tsx
- packages/ui/react/src/components/Primitives/Dropdown/index.ts
- packages/ui/react/src/components/Primitives/Icon/Icon.stories.tsx
- packages/ui/react/src/components/Primitives/Icon/Icon.test.tsx
- packages/ui/react/src/components/Primitives/Icon/Icon.tsx
- packages/ui/react/src/components/Primitives/Icon/index.ts
- packages/ui/react/src/components/Primitives/Link/Link.stories.tsx
- packages/ui/react/src/components/Primitives/Link/Link.styled.ts
- packages/ui/react/src/components/Primitives/Link/Link.test.tsx
- packages/ui/react/src/components/Primitives/Link/Link.tsx
- packages/ui/react/src/components/Primitives/Link/index.ts
- packages/ui/react/src/components/Primitives/Tooltip/Tooltip.tsx
- packages/ui/react/src/components/Primitives/index.ts
- packages/ui/react/src/components/README.md
- packages/ui/react/src/components/helpers.ts
- packages/ui/react/src/components/types.ts
- packages/ui/react/tsconfig.json
- Add `Dropdown` component to library and its dependent components: Icon and Link
- Add `getOpacity` helper to handle color opacity
- Fixes types exported, see more details on `.changeset/fix-type-import-paths.md`
N/A
1. Dropdown Component available in @devopness/ui-react
2. Types being imported from correct paths after build
[DVN-16437]
[DVN-16524]
[DVN-16437]: https://devopness.atlassian.net/browse/DVN-16437?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(design-system): add dropdown component and fixes exported types

- .changeset/config.json
- .github/workflows/release.yml
- package-lock.json
- package.json
- Update changelog generator from `@changesets/cli` to `@changesets/changelog-github` [1]
- Changelog mentions contributors
- Update release.yml config
- PR titles updated from "Version Packages" to "chore: version packages"
N/A
- Version packages PR title must be "chore: version packages"
- Changelogs must mention contributors
https://github.com/thlmenezes/devopness/pull/5
[1]
BEFORE:
AFTER:
> ci(release): add contributor mention to generated changelogs

- docs/users/subscriptions/faq/index.md
Clarified documentation on how credit usage is calculated for pipeline actions. Added examples for both simple actions (single-step) and complex actions (multi-step), emphasizing that **only successful steps** consume credits. This aims to improve transparency for Devopness users regarding credit consumption.
- Users will understand how credits are consumed, especially for complex actions like multi-step pipelines.
- Documentation updated under `docs/users/subscriptions/faq/index.md` to include the new details. 
- These changes were initially suggested in response to [this comment](https://github.com/devopness/devopness/pull/1011#discussion_r1846972805) on PR #1011. However, since that PR was already merged, I …
> docs: clarify credit consumption details in FAQs

- .changeset/add-target-human-readable-in-variable.md
- packages/sdks/javascript/src/api/generated/models/variable-relation.ts
- packages/sdks/javascript/src/api/generated/models/variable.ts
- packages/sdks/javascript/src/api/spec.json
- Add **target_human_readable** property to the _Variable_ model
- Add **target_human_readable** property to the _VariableRelation_ model
> feat: 2024-11-20 11:05 - Update API specification

- .changeset/add-azure-rm-in-cloud-provider-services-enum.md
- .changeset/add-region-human-readable-field-in-subnet.md
- .changeset/create-azure-model-for-subnet-provision-input-settings.md
- packages/sdks/javascript/src/api/generated/models/cloud-provider-service-code.ts
- packages/sdks/javascript/src/api/generated/models/index.ts
- packages/sdks/javascript/src/api/generated/models/subnet-provision-input-settings-aws.ts
- packages/sdks/javascript/src/api/generated/models/subnet-provision-input-settings-azure.ts
- packages/sdks/javascript/src/api/generated/models/subnet-provision-input-settings-gcp.ts
- packages/sdks/javascript/src/api/generated/models/subnet-provision-input-settings.ts
- packages/sdks/javascript/src/api/spec.json
> feat: 2024-12-05 12:12 - Update API specification 

- .changeset/changed-fields-of-pipeline-step-model.md
- packages/sdks/javascript/src/api/generated/models/step-pipeline-create.ts
- packages/sdks/javascript/src/api/generated/models/step-pipeline-update.ts
- packages/sdks/javascript/src/api/generated/models/step.ts
- packages/sdks/javascript/src/api/spec.json
> feat: 2024-12-05 18:03 -  Update API specification

- docs/servers/rotate-key.md
N/A
- Once the changes in this PR are merged and deployed, success criteria is: The new documentation article will be included on Devopness' documentation.
N/A
> docs: add article about server's rotate key

- .changeset/add-description-field-in-action-target.md
- .changeset/add-server-rotate-key-operation.md
- packages/sdks/javascript/src/api/generated/apis/servers-api.ts
- packages/sdks/javascript/src/api/generated/models/action-step.ts
- packages/sdks/javascript/src/api/spec.json
> feat: 2024-12-13 13:55 - Update API specification

- .changeset/fix-ErrorMessage-types.md
- packages/ui/react/src/components/Primitives/ErrorMessage/ErrorMessage.tsx
The ErrorMessage component was failing to work with various error formats due to strict type constraints. This fix adds support for custom error types to resolve these compatibility issues
N/A
- ErrorMessage component can be used with a wider range of components that need to display errors
> fix(design-system): enhance ErrorMessage type definition flexibility

- .changeset/support-ubuntu-24-04.md
- packages/sdks/javascript/src/api/generated/models/cloud-os-version-code.ts
- packages/sdks/javascript/src/api/spec.json
> feat: 2025-01-19 16:08 - Update API specification 

- docs/credentials/add-aws-credential.md
> docs: Improving clarity in navigating AWS section and adding extra section with was excluded. Update add-aws-credential.md

- packages/ui/react/src/components/README.md
- Create component development guide
N/A
- Once the changes in this PR are merged and deployed, success criteria is: People aiming to contribute to the component library inside the design system should have a guide to help them succeed
> docs(design-system): add component development guide

- .github/workflows/pr-lint.yml
- N/A  
- Once the changes in this PR are merged and deployed, the success criteria is: PRs from the user [devopness-automations](https://github.com/devopness-automations) will no longer be checked by the `PR Lint` CI.  
- PR from [devopness-automations](https://github.com/devopness-automations) blocked by the `PR Lint` CI - [#1252](https://github.com/devopness/devopness/actions/runs/13040682748/job/36381621847?pr=1252)
> fix: update PR validation to exclude multiple users from checks

- packages/sdks/javascript/src/api/generated/models/action-type.ts
- packages/sdks/javascript/src/api/spec.json
> feat: 2025-01-29 20:27 - Update API  specification

- .changeset/add_team_memberships_in_environment_relation_models.md
- .changeset/change_credentials_field_type_in_server_model_to_nullable.md
- packages/sdks/javascript/src/api/generated/models/archived-environment-relation.ts
- packages/sdks/javascript/src/api/generated/models/environment-relation.ts
- packages/sdks/javascript/src/api/generated/models/server-relation.ts
- packages/sdks/javascript/src/api/spec.json
> feat: 2025-02-11 22:45 - Update API specification

- .changeset/update-iconLoader-paths.md
- packages/ui/react/src/icons/iconLoader.tsx
- N/A
- IconLoader will be able to find the icons through the correct path
> fix: update iconLoader to match new assets paths

- .changeset/human-readable-fields-for-programming-language-and-framework-in-application-models.md
- packages/sdks/javascript/src/api/generated/models/application-relation.ts
- packages/sdks/javascript/src/api/generated/models/application.ts
- packages/sdks/javascript/src/api/spec.json
> feat: 2025-02-19 12:20 - Update API specification

- examples/applications/README.md
- examples/applications/ruby-rails/README.md
- Once the changes in this PR are merged and deployed, success criteria is: we will have a well-defined process for providing example applications to be deployed via Devopness. 
[DVN-17729]: https://devopness.atlassian.net/browse/DVN-17729?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(examples): add rails app example README

- docs/variables/add-variable.md
- docs/variables/edit-variable.md
- docs/variables/index.md
- docs/variables/remove-variable.md
- Once the changes in this PR are merged and deployed, success criteria is: documentation of variables follows the guidelines defined in [Devopness Documentation - Guideline](https://github.com/devopness/devopness/tree/main/docs#what-should-not-be-included-in-the-documentation).
<details><summary>Variables</summary>
</details> 
<details><summary>Add Variable</summary>
</details> 
<details><summary>Edit Variable</summary>
</details> 
<details><summary>Remove Variable</summary>
</details> 
[DVN-17770]: https://devopness.atlassian.net/browse/DVN-17770?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DVN-17769]: https://devopness.atlassian.net/browse/DVN-17769?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1ci …
> docs(variables): remove deprecated 'intro' field and use admonition

- README.md
* Updated the GitHub Actions badge link in README.md to reflect the workflow filename change from `sdk-javascript-ci.yml` to `ci-sdk-javascript.yml`.
- N/A
- Once merged, the badge should display correctly and link to the proper GitHub Actions workflow history page
N/A
> docs: update GitHub Actions workflow badge link

- packages/sdks/javascript/src/api/spec.json
> feat: 2025-03-25 20:24 - Update API specification

- .github/workflows/pr-auto-merge-dependabot.yml
- N/A
- Once the changes in this PR are merged and deployed, success criteria is: Patch and minor version updates from Dependabot are automatically merged.
> refactor(ci): allow patch and minor updates in Dependabot auto-merge

- packages/sdks/python/.version
- packages/sdks/python/devopness/client.py
- packages/sdks/python/devopness/services/cron_job_service.py
- packages/sdks/python/devopness/services/daemon_service.py
- packages/sdks/python/devopness/services/environment_service.py
- packages/sdks/python/devopness/services/service_service.py
- packages/sdks/python/devopness/services/ssh_key_service.py
- N/A
- contribute to #921
- The cron-job service are available and functional in the SDK
- The daemon service are available and functional in the SDK
- The 'service' service are available and functional in the SDK
- The ssh-key service are available and functional in the SDK
> feat(sdk-python): expose cron-job, daemon, service and ssh-key services in Devopness Client

- .changeset/curly-doors-cough.md
- packages/sdks/common/spec.json
- packages/sdks/javascript/src/api/generated/models/action-deployment-content.ts
- packages/sdks/python/devopness/generated/models/action_deployment_content.py
> feat: 2025-05-02 23:08 - Update API specification

- .changeset/vast-maps-count.md
- packages/sdks/common/spec.json
- packages/sdks/javascript/src/api/generated/models/action-type.ts
- packages/sdks/python/.version
- packages/sdks/python/devopness/generated/models/action_type.py
> feat: 2025-05-06 00:18 - Update API specification

- .changeset/angry-tigers-yawn.md
- packages/sdks/common/spec.json
- packages/sdks/javascript/src/api/generated/models/action-target.ts
- packages/sdks/python/.version
- packages/sdks/python/devopness/generated/models/action_target.py
> feat: 2025-05-07 20:53 - Update API specification

- packages/sdks/python/.version
- packages/sdks/python/devopness/client.py
- packages/sdks/python/devopness/services/action_service.py
- packages/sdks/python/devopness/services/pipeline_service.py
- packages/sdks/python/devopness/services/resource_link_service.py
- packages/sdks/python/devopness/services/variable_service.py
- packages/sdks/python/tests/unit/test_client.py
- N/A
- contribute to #921
- All newly exposed services are available via the SDK
> feat(sdk-python): expose actions, pipelines, resource links, and variables service in client

- .changeset/expose-services.md
- packages/sdks/python/devopness/client.py
- packages/sdks/python/devopness/services/action_service.py
- packages/sdks/python/devopness/services/application_service.py
- packages/sdks/python/devopness/services/environment_service.py
- packages/sdks/python/devopness/services/hook_service.py
- packages/sdks/python/devopness/services/network_rule_service.py
- packages/sdks/python/devopness/services/organization_service.py
- packages/sdks/python/devopness/services/pipeline_service.py
- packages/sdks/python/devopness/services/project_service.py
- packages/sdks/python/devopness/services/resource_event_service.py
- packages/sdks/python/devopness/services/role_service.py
- packages/sdks/python/devopness/services/social_account_service.py
- packages/sdks/python/devopness/services/ssl_certificate_service.py
- packages/sdks/python/devopness/services/static_service.py
- packages/sdks/python/devopness/services/team_service.py
- packages/sdks/python/devopness/services/user_service.py
- packages/sdks/python/tests/unit/test_client.py
This PR significantly enhances the Devopness SDK for Python by exposing several services through the `Devopness Client`.
* N/A
* [DVN-18045](https://linear.app/devopness/issue/DVN-18045/sdk-expose-all-services-in-client)
* Once the changes in this PR are merged and deployed, success criteria is:
- All listed services should be accessible through `DevopnessClient`, with full test coverage ensuring they are functional and properly integrated.
N/A
> feat(sdk-python): expose new services in client and improve test coverage

- .changeset/breezy-emus-kneel.md
- packages/sdks/common/spec.json
- packages/sdks/javascript/src/api/generated/models/cloud-instance-relation.ts
- packages/sdks/python/src/devopness/generated/models/cloud_instance_relation.py
> feat: 2025-05-20 14:51 -  Update API specification

- .github/workflows/ci-sdk-javascript.yml
- .github/workflows/ci-sdk-python.yml
- .github/workflows/release-packages.yml
- package-lock.json
* The workflow responsible for managing package versions has been updated to include a new job: **update-lockfile-after-release**. This job ensures that the root **package-lock.json** is updated after the release of workspace packages (e.g. **ui-react**, **sdk-js**, **sdk-python**)
- New variables **DEVOPNESS_AUTOMATIONS_USERNAME** and **DEVOPNESS_AUTOMATIONS_EMAIL** were added to replace hardcoded values across workflows. All relevant workflows were updated to use these variables instead of directly exposing the name and email
* N/A
* Once the changes in this PR are merged and deployed, success criteria is:
* **package-lock.json** is consistently updated to reflect the latest workspace versions after each release, and automation metadata is managed via environment variables
> chore: update package-lock.json after releasing packages

- .changeset/moody-chicken-draw.md
- packages/ai/mcp-server/src/devopness_mcp_server/lib/tools.py
- packages/ai/mcp-server/uv.lock
- If the user provides a `pipeline_id`, the tool uses it directly to trigger the deployment
- If the user only knows the `application_id`, the tool returns a list of available deploy pipelines for that application
- The LLM is instructed to ask the user to select a pipeline and then re-call the tool with the chosen `pipeline_id`
- N/A
- Users can trigger deployments by providing either a `pipeline_id` or an `application_id`
- When only `application_id` is provided, the tool returns a list of pipelines and guides the user to select one before proceeding
<details><summary>Example: User Deploy Application with Devopness MCP
</summary>
| Persona | Message |
| - | - |
| User | Help me to deploy the application with ID …
> feat(mcp-server): devopness_deploy_application tool support pipeline selection by application id

- package-lock.json
- packages/ai/mcp-server/package.json
- packages/ai/mcp-server/pyproject.toml
- N/A
- Once the changes in this PR are merged and deployed, success criteria is: a new version of mcp server will be released
> chore: package version

- README.md
- package-lock.json
- packages/ai/mcp-server/README.md
- packages/ai/mcp-server/package.json
- packages/ai/mcp-server/pyproject.toml
- N/A
- Once the changes in this PR are merged and deployed, success criteria is: all typos have been fixed
> fix: typos in mcp-server readme file

- .changeset/itchy-crabs-approve.md
- package-lock.json
- packages/sdks/common/spec.json
- packages/sdks/javascript/package-lock.json
- packages/sdks/javascript/src/api/generated/models/user-update.ts
- packages/sdks/python/src/devopness/generated/models/user_relation.py
- packages/sdks/python/src/devopness/generated/models/user_update.py
> feat: 2025-06-23 16:59 - Update API specification

- .changeset/moody-donkeys-judge.md
- packages/ai/mcp-server/src/devopness_mcp_server/lib/devopness_api.py
- packages/ai/mcp-server/src/devopness_mcp_server/lib/models.py
- packages/ai/mcp-server/src/devopness_mcp_server/lib/response.py
- packages/ai/mcp-server/src/devopness_mcp_server/lib/services/application_service.py
- packages/ai/mcp-server/src/devopness_mcp_server/lib/services/credential_service.py
- packages/ai/mcp-server/src/devopness_mcp_server/lib/services/environment_service.py
- packages/ai/mcp-server/src/devopness_mcp_server/lib/services/pipeline_service.py
- packages/ai/mcp-server/src/devopness_mcp_server/lib/services/project_service.py
- packages/ai/mcp-server/src/devopness_mcp_server/lib/services/server_service.py
- packages/ai/mcp-server/src/devopness_mcp_server/lib/services/service_service.py
- packages/ai/mcp-server/src/devopness_mcp_server/lib/services/ssh_key_service.py
- packages/ai/mcp-server/src/devopness_mcp_server/lib/tools.py
- packages/ai/mcp-server/src/devopness_mcp_server/lib/types.py
- packages/ai/mcp-server/src/devopness_mcp_server/lib/utils.py
This PR refactors all MCP Server listing tools to enforce consistent pagination using a fixed page size (`MAX_RESOURCES_PER_PAGE = 5`) and standardized output formatting.
It introduces simplified data models for each MCP Server resource, derived from the SDK models, containing only essential fields to reduce payload size and minimize hallucination risks in LLM interactions.
Key changes include:
* All listing tools now require `project_id` to build web app resource links and use utility functions for uniform list formatting.
* Listing outputs include clear next step suggestions, such as "deploy application," guiding users on what to do after listing resources.
* Deployment tools were refactored to require `pipeline_id` and a list of `server_ids`, and to use utility functions for consistent …
> refactor(mcp-server): standardize listing tools with pagination and clear output formatting rules

- packages/ai/mcp-server/src/devopness_mcp_server/lib/services/ssl_certificate.py
- This should have been included in PR https://github.com/devopness/devopness/pull/1896, but was unintentionally left out
- N/A
- Deploy tool for ssl-certificate is available and functioning as expected
> fix(mcp-server): add deploy tool  for ssl-certificate

- .github/workflows/ci-docs.yml
- N/A
- Once the changes in this PR are merged and deployed, success criteria is: docs build is successful, using a `.env` file
Original error: https://github.com/devopness/devopness/actions/runs/15911568303/job/44879998551#step:5:21
> ci: ensure a `.env` file used to build docs web

- README.md
- N/A
- Add Button correctly configures the MCP Server
> chore: update MCP 'add button' command

- README.md
- N/A
- Once the changes in this PR are merged and deployed, success criteria is: Add button successfully uses the remote version of Devopness MCP.
> chore: mcp 'add buttons' use remote Devopness MCP

- .changeset/chatty-pumas-change.md
- packages/sdks/common/spec.json
- packages/sdks/javascript/src/api/generated/apis/variables-api.ts
- packages/sdks/javascript/src/api/generated/models/variable-relation.ts
- packages/sdks/javascript/src/api/generated/models/variable.ts
- packages/sdks/python/src/devopness/generated/api/variables_api.py
- packages/sdks/python/src/devopness/generated/models/variable.py
- packages/sdks/python/src/devopness/generated/models/variable_relation.py
> feat: 2025-07-03 18:17 - Update API specification

- .changeset/fair-baboons-accept.md
- packages/sdks/common/spec.json
- packages/sdks/javascript/src/api/generated/models/action-retry-response.ts
- packages/sdks/javascript/src/api/generated/models/action-target.ts
- packages/sdks/javascript/src/api/generated/models/action.ts
- packages/sdks/python/src/devopness/generated/models/action.py
- packages/sdks/python/src/devopness/generated/models/action_retry_response.py
- packages/sdks/python/src/devopness/generated/models/action_target.py
> feat: 2025-07-08 21:47 - Update API specification

- .github/workflows/ci-cla-assistant.yml
- N/A
- Once the changes in this PR are merged and deployed, success criteria is: PRs generated by contributors using Cursor IDE should not require cursor to sign the CLA, just the user creating the PR or committing to the PR branch will need to sign the CLA
> ci: update CLA allow list
